In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
def create_poly_data(size=100):
    x = 6 * np.random.rand(size,1) - 3
    
    y = 0.5 * x**2 + x + 5 + np.random.randn(size,1)
    return x,y

In [3]:
def plot_data(x,y,y_pred=None):
    
    if y_pred is not None:
        
        if x.ndim != 1 and y.ndim != 1:
            raise ValueError("x and y dimension must be 1D")
        
        x_y = np.array([x,y]).T
    
    plt.scatter(x,y)
    plt.show()
    

In [4]:
x,y = create_poly_data(10)

In [23]:
def pair_xy(x,y):
    """Pair the x and y data point with 1D data, Note that x and y data point must be 1D 
    or a columns vector. if column vector is provided then it will be converted to the 1D
    array"""
    
    if x.ndim == 2  
    

SyntaxError: expected ':' (815973153.py, line 6)

In [22]:
x.ravel().ndim

1

In [21]:
sorted_item =  np.lexsort(x)

In [22]:
sorted_item

array([0], dtype=int64)

In [33]:
np.array()

SyntaxError: did you forget parentheses around the comprehension target? (221884753.py, line 1)

In [31]:
x[0]

array([-1.65976524])

In [48]:
[ (x[i,0], y[i,0]) for i in np.argsort(x, axis=0).ravel()]

[(-2.6334973021971533, 4.687329667653917),
 (-2.1680110867397953, 6.217179073344907),
 (-1.6957551395844355, 4.779033130710317),
 (-1.6597652380328423, 5.17330659706402),
 (-1.6350395933306252, 4.537104474983028),
 (-1.3619926185345803, 4.6277370633565615),
 (-0.31074726142940534, 3.6574207109805803),
 (-0.20763808311081355, 4.3570371842848985),
 (0.24722240954435293, 5.500863009640093),
 (0.6233254217899491, 5.232640358792393)]

In [49]:
np.array([ (x[i,0], y[i,0]) for i in np.argsort(x, axis=0).ravel()])

array([[-2.6334973 ,  4.68732967],
       [-2.16801109,  6.21717907],
       [-1.69575514,  4.77903313],
       [-1.65976524,  5.1733066 ],
       [-1.63503959,  4.53710447],
       [-1.36199262,  4.62773706],
       [-0.31074726,  3.65742071],
       [-0.20763808,  4.35703718],
       [ 0.24722241,  5.50086301],
       [ 0.62332542,  5.23264036]])

In [14]:
 a =np.array([x[:,0],y[:,0]]).T

In [16]:
a

array([[-1.30427847,  4.85032962],
       [ 2.42556047,  9.36952385],
       [-0.39577581,  4.0495563 ],
       [ 2.65645272, 10.06214705],
       [ 1.33329692,  4.78460354],
       [ 2.8163019 , 10.47757485],
       [-2.51895172,  6.67600844],
       [ 0.87190501,  5.62703322],
       [ 2.62808966, 11.77555873],
       [ 2.19180187,  9.09850834]])

In [12]:
a

array([[-1.30427847,  2.42556047, -0.39577581,  2.65645272,  1.33329692,
         2.8163019 , -2.51895172,  0.87190501,  2.62808966,  2.19180187],
       [ 4.85032962,  9.36952385,  4.0495563 , 10.06214705,  4.78460354,
        10.47757485,  6.67600844,  5.62703322, 11.77555873,  9.09850834]])

In [13]:
np.array([x,y])

array([[[-1.30427847],
        [ 2.42556047],
        [-0.39577581],
        [ 2.65645272],
        [ 1.33329692],
        [ 2.8163019 ],
        [-2.51895172],
        [ 0.87190501],
        [ 2.62808966],
        [ 2.19180187]],

       [[ 4.85032962],
        [ 9.36952385],
        [ 4.0495563 ],
        [10.06214705],
        [ 4.78460354],
        [10.47757485],
        [ 6.67600844],
        [ 5.62703322],
        [11.77555873],
        [ 9.09850834]]])