In [1]:
import numpy as np
from numpy import arange , ndarray
from numpy.random import randint , choice

# Indexing

Indexing is a method to access an item of an object by using their contigous loaction like array.  Since we are working on the array and numpy arrays are N-dimensioal so there are some complexity comes when we try to access an item by using indexing in a N-dimensional array. Now we will try to understand them by starting from a single item accessing in 1D array.

In this section for now we will only see upto 3-dimesional array.

### 1. Access an item from a single array:

first of all we need an array so we will create an array with arange function.

In [3]:
array =  arange(10)

# Now we have an array let's print it 
print("Array: ", array)

Array:  [0 1 2 3 4 5 6 7 8 9]


Now if we want to access any item from like 7 then we need to start from 0 because indexing always starts from 0, so if we want to access it then we need to count from 0 to up to the element position in this case element 7 is at the index number 7th.

In [5]:
# To access an element we need to use the square bracket [] after the array object like 
# array[index]

array[7]

7

As you can see that we have got 7 now we will use an random number array to see the it againl.

In [9]:
# creating an random array with randint

array = randint(1,50,size=(20,))
print("array: ", array)

array:  [13 25 33 36 36  2  1 41 31  7 47 36 48 28 45 46  7 46 29  9]


As you can see that we have a new random array in which all are int type not lets say we want to access 10th element of the array. then we need to pass `(n-1)` for the indexing. We can see that the 10th element is 7 and by using indexing we will access it.

In [10]:
# accessing the 10th element
array[9] # (n-1) indexing number 

7

In [11]:
# accessing teh 15th element
array[14]

45

**Reversive indexing**

We can access the 14th element from the right side of the array by using the negative indexing [-n]. Like , if we want to access the 15th element of the array then we count it from the right side and put a negative sign on the number at which the element is present. Like 45 is present at the 6th location from right side of the array then we need to use indexing like this `array[-6]`.

In [12]:
# accessing the 15th element form the right side (negagtive indexing.)
array[-6]

45

## Single element idexing with 2-d array

Since Numpy contains N-dimensional array like this 2-d array also comes in the N-dimensional but in 2d array we have only two sub array in a single thats why its dimension is 2d. Now when we create an 2d array then there are two thing comes in picture these are Row and Column of the array which can be seen like this `array[Row ,  Column]`.

Let's see how it looks like:

In [14]:
# creating a 2d array
array = randint(1,20,size=(5,4))
print("2D array:\n", array)
print("\nShape of the array:",array.shape)
print("Dimension of the array: ",array.ndim)

2D array:
 [[ 1 10 17 16]
 [ 9 11 10  8]
 [ 1 14 19 19]
 [17  7 16  8]
 [ 4 15  1 18]]

Shape of the array: (5, 4)
Dimension of the array:  2


As you can see that we have got an  2d array and also we have checked its shape and the dimension with `shape` and `ndim` property of the array. Now since it is a two dimension then we need also two index number one is for the `rows` of the array and the other number is for the the `Column` of the array.

In [16]:
# accessing  an item from the 2d array
# So we need Rows number and Column number to access the element of the array 
# sicne from the shape of the array we can see that new array conatains 5 Rows and 4 Columns for we cant got beyond these numbers.

# Lets acces an element which is present in 3rd row and 2nd Conlumn
array[2,1] # 2 is for the row indexing and 1 is for the column indexing 

# Since indexing starts from the 0 number 

14

In [17]:
array

array([[ 1, 10, 17, 16],
       [ 9, 11, 10,  8],
       [ 1, 14, 19, 19],
       [17,  7, 16,  8],
       [ 4, 15,  1, 18]])

As you can see in above array then element 14 is placed at the 3rd row and 2nd column. So we have seen that for accessing an element in a 2d array we need two indexing number first one is for the `Rows` of the array and the other one if for `Columns` of the array.

## Selecting a Row or a Column of an arrray:

After selecting an array we will select an entire Row and an entire Column of the array. Because we have already have an 2D array so we don't need to make another one.

In [18]:
# Printing the over old 2D array 
print(array)

[[ 1 10 17 16]
 [ 9 11 10  8]
 [ 1 14 19 19]
 [17  7 16  8]
 [ 4 15  1 18]]


**Selecting an Row of 2D array**

Selecting a row and Column is very simple we just need to give only one number any of two number `(Rows and Column)`. if we want to select a row then we need to give that rows number. Like we want to select 3rd row then we need to use the `array[2]`. 

In this we are only accessing Row element and do not specifing any colulmns, by doing this it will count all the column and return all the items from all the column.

In [19]:
# Accessing 3rd row of the array
array[2]

array([ 1, 14, 19, 19])

In [20]:
# the above accesing of 3rd row is also written as
array[2,:]

array([ 1, 14, 19, 19])

Here `:` represents slicing of the element which has the real representation as `n1:n2` . but in the above cell we didn't provide any n1 and n2  and the single `:` represents that we need all the element of the current dimension and in this case the current dimension is Column of the array.

**Accessing Column of the array**

Like Accessing the row of the array , selection of column is also similar to the the selection of the row, we just need to left blank the rows indexing and just need to specify the column which we want to access.


In [21]:
# Like we want to access 3rd Column of the array
# we need to left empty of the rows index

array[,2]

SyntaxError: invalid syntax (<ipython-input-21-873bd565f691>, line 4)

OH NOO! We have got an error but we left the rows place empty and provided the columns index number then what is wrong with it. 

The problem is that here empty means we need to specify `:` to the rows. it means that we need all from this dimenion (row). So let's try again with `:` this.

In [22]:
array[:,2]

array([17, 10, 19, 16,  1])

See that we have got the 3rd column of the array. Now we will access a section of an array.

## Select a section of a 2D-array:

Lets say that we have a big 2D array of 36 element which is 6 x 6  and we want to access a particular section of that array then we need to use the slicing of the array which can be done by using `n1:n2` in a that dimension in which we want to slice the array. 

First of all we will make a new big array:

In [25]:
# Making a 6 x 6 array
array = randint(1,100, size = (6,6))
print("Array: \n",array)
print("\nShape of the array:", array.shape)
print("Total elements in the array: ", array.size)

Array: 
 [[85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [55 24 52 38 81 11]
 [ 6 89 92 65 39 19]
 [62 45 57 25 94 88]
 [84 62  9 26 57 47]]

Shape of the array: (6, 6)
Total elements in the array:  36


Now from the above output we can see that we have an 2D array with a shape of (6,6 ) and it has 36 elements. So now we need to select a particular area of the element.
```ruby
 array =      [[24 52 38]
               [89 92 65]
               [45 57 25]]
```

Now we will select the above section of the current array:

In [26]:
# To select this kind of section we need to use the slicing of the array n1:n2
# we need slicing in the both row and column so we need to use like this

# array[n1:n2 , n1:n2]

# first n1:n2 is for the slicing of the the Rows
# Second n1:n2 is for the slicing of the columns

# we can write this as also --------> array[start:end , start:end]
# This clear the confusion that we need a starting point and ending point in both rows and columns

# now count the rows starting point and ending point of the rows and columns
# rows----> 2:4  # these are index nunbers not position number
# column------> 1:3

# Now accessing the section
array[2:4 , 1:3]

array([[24, 52],
       [89, 92]])

Oh no....! the result is not seem to match our task, So what happened.

`Note:` End point in the slicing is not inclusive so we need of proved the `n+1` in the end indexing point. So our New slicing becomes as.

Rows = 2:5 

Columns = 1:4


In [27]:
# accessing again
array[2:5, 1:4]

array([[24, 52, 38],
       [89, 92, 65],
       [45, 57, 25]])

Now we can see that, we have got our desired result but the thing is to be remember is that `end` point in the slicing of the array dimension is not inclusive so we need to provide `(n+1)`  index number to get the desired result.

#### Selection without start or end point:

Selection without start point or end point is used when we need to slice something from begning of the column or the row and slicing something upto end of the rows and the columns.

**Example 1**
```ruby
array([[85, 10, 91],
       [21, 30, 20],
       [55, 24, 52],
       [ 6, 89, 92]])
```

Select this setion from the array:(old array which is used in previous selection)

In [30]:
# printing array again
print(array)

[[85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [55 24 52 38 81 11]
 [ 6 89 92 65 39 19]
 [62 45 57 25 94 88]
 [84 62  9 26 57 47]]


As from the example 1 task we can see that section starts from 0th row and 0th column, in this case we do not need to provide the starting point during the slicing of the array. we can use `array[:end, :end]` like slicing beacause both start point are at 0th indexing.

In [31]:
# accesing the given array on example 1
array[:4,:3] # since we need first four rows 0 to 3 ||| and we need first three column from 0 to 2 
# Since end point of indexing need to provide as (n+1)

array([[85, 10, 91],
       [21, 30, 20],
       [55, 24, 52],
       [ 6, 89, 92]])

As you can see that we have got our result.

**Example 2**

```ruby
array([[39, 19],
       [94, 88],
       [57, 47]])
```

In [38]:
# Count the rows and columns to match the start:points of exampel 2 section

# Rows------------>  3:6  # since we have only 6 rows so we can write this as => 3: this says count all the rows after 3rd row
# Columns--------->  4:6  # can be written as => 4: count all column after 4
array[3:, 4:]

array([[39, 19],
       [94, 88],
       [57, 47]])

**Example 3**

```ruby
array([[21, 30, 20, 94],
       [55, 24, 52, 38],
       [ 6, 89, 92, 65]])
```

In [39]:
# Count the rows and columns to match the start:points of exampel 4 section

# Rows------------>  1:(3+1)  
# Columns--------->  0:(3+1)  can be written as => :4

array[1:4 , :4]

array([[21, 30, 20, 94],
       [55, 24, 52, 38],
       [ 6, 89, 92, 65]])

**Example 4**
```ruby
array([[20, 94, 45, 37],
       [52, 38, 81, 11],
       [92, 65, 39, 19]])
```

In [40]:
# Count the rows and columns to match the start:points of exampel 4 section

# Rows------------>  1:(3+1)  
# Columns--------->  2:6  can be written as => 2:

array[1:4 , 2:]

array([[20, 94, 45, 37],
       [52, 38, 81, 11],
       [92, 65, 39, 19]])

`Conclusion:` From  all of the above example in the slection (slicing) of an array  gives us the overall overview that we can access any section of the array with the help of the slicing in this syntex `array[start:end+1 , start:end+1]`. Since end point is not inclusive in the slicing.

***
***

## Index arrays with other arrays
NumPy arrays may be indexed with other arrays (or any other sequence- like object that can be converted to an array, such as lists, with the exception of tuples; see the end of this document for why this is). The use of index arrays ranges from simple, straightforward cases to complex, hard-to-understand cases. For all cases of index arrays, what is returned is a copy of the original data, not a view as one gets for slices.


In [48]:
# like we have and array which is showing below
print(array)

[[85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [55 24 52 38 81 11]
 [ 6 89 92 65 39 19]
 [62 45 57 25 94 88]
 [84 62  9 26 57 47]]


In [49]:
# now we have another array 
seq = np.arange(6)
print(seq)

[0 1 2 3 4 5]


Now we will pass this array into the our old array on which we are working.

In [50]:
# poassing the seq into the array
array[seq]

array([[85, 10, 91, 31, 56, 51],
       [21, 30, 20, 94, 45, 37],
       [55, 24, 52, 38, 81, 11],
       [ 6, 89, 92, 65, 39, 19],
       [62, 45, 57, 25, 94, 88],
       [84, 62,  9, 26, 57, 47]])

As you can see that we have got the same result but this is not the same as the simple call of `array` because this time we have selected the rows with the help of the another sequence which is like another array. you can see that our seq contains [0 1 2 3 4 5] which are the index numbers of the `array's` rows and by putting this seq into the array we select every row of the array.

Now this time we will make a random array and we will use that to select the row of the array.

In [57]:
# random array 
seq = randint(6, size=[6,])
print(seq)

[5 4 0 1 4 3]


In [61]:
# selecting the random rows by using the random values which are inside a seq
print("Original array: \n",array)
print("\nSelected array:\n",array[seq])

Original array: 
 [[85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [55 24 52 38 81 11]
 [ 6 89 92 65 39 19]
 [62 45 57 25 94 88]
 [84 62  9 26 57 47]]

Selected array:
 [[84 62  9 26 57 47]
 [62 45 57 25 94 88]
 [85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [62 45 57 25 94 88]
 [ 6 89 92 65 39 19]]


As you can see that we this time also we have selected 6 row but these 6 rows are not in  order if you look carefully you can found that there is a difference b/e the `Original array` and the `Selected array`. In selected array we have choosen 4th number of index twice and these are placed at 1st and 4h number of index in selected array.

`Conclusion:` Now we have understand that an array like sequence which contains some integer which are not greater than the index number of the array then these number is treated as the index number of the array. They also can be used  in slicing .

##### What if we have a sequence containing numbers greater than  index numbers?

In [62]:
seq = np.arange(8)
print(seq)

[0 1 2 3 4 5 6 7]


We have a seq which contains the nmbers which are greater than then index of our curent array.

Our current array is :


In [63]:
array

array([[85, 10, 91, 31, 56, 51],
       [21, 30, 20, 94, 45, 37],
       [55, 24, 52, 38, 81, 11],
       [ 6, 89, 92, 65, 39, 19],
       [62, 45, 57, 25, 94, 88],
       [84, 62,  9, 26, 57, 47]])

In [64]:
# passing the sequenct into the array:
array[seq]

IndexError: index 6 is out of bounds for axis 0 with size 6

As you can see that we have got `IndexError` as we thought because it contains some vaues whcih are greater then the index or they do not meet to he index range. 

### Slicing with sequence

Since a sequence contains some interger which meets to the index range of the array then they can be used to slice the array:

In [66]:
# Now we will use two random seq
seq1   = randint(6, size=[3])
seq2   = randint(6, size=[3])

print(seq1 , seq2)

[1 1 5] [3 4 3]


Now we have two sequece which are random and also in the range of the index of the current array:

In [67]:
# printing the current array again
array

array([[85, 10, 91, 31, 56, 51],
       [21, 30, 20, 94, 45, 37],
       [55, 24, 52, 38, 81, 11],
       [ 6, 89, 92, 65, 39, 19],
       [62, 45, 57, 25, 94, 88],
       [84, 62,  9, 26, 57, 47]])

***Example 1***

In [68]:
array[seq1:seq2]

TypeError: only integer scalar arrays can be converted to a scalar index

***Example 2***

In [69]:
array[seq1:]

TypeError: only integer scalar arrays can be converted to a scalar index

***Example 3 Combining index arrays with slices***

In [70]:
array[seq1, 1:3]

array([[30, 20],
       [30, 20],
       [62,  9]])

***Example 4 Combining index arrays with slices***

In [71]:
array[1:3, seq2]

array([[94, 45, 94],
       [38, 81, 38]])

From the example 1,2 we have seen that we cant do the slicing by using the seq1:seq2 becaues because for slicing we need only single integer value not a sequence of the integer.

From the example 2,3 we have seen that we can use the slicing and seq combination but they must be used in the seperate dimension like in above example we have used slicing in row and index array used in column or vise -versa.

### Indexing wiht multi-dimensional arrays.

Multi-dimesional array are not used often but they are permitted in the array indexing. Multi-dimensional index arrays are complex to use but they are very usefull for some problems.

The shape of the output array after using the 'multi-dimensional index array'  will be equal to the shape of the index array if their values are in the range of the index of  the array.

For this section also we will use the old array which are being used in the above sections and also we have two sequence seq1 and seq2.

In [72]:
# printing the array
array

array([[85, 10, 91, 31, 56, 51],
       [21, 30, 20, 94, 45, 37],
       [55, 24, 52, 38, 81, 11],
       [ 6, 89, 92, 65, 39, 19],
       [62, 45, 57, 25, 94, 88],
       [84, 62,  9, 26, 57, 47]])

In [73]:
# printing the sequences

print(seq1)
print(seq2)

[1 1 5]
[3 4 3]


In [74]:
# using the multi dimensional array
array[seq1, seq2] # length of the seq1 == seq2

array([94, 45, 26])

**What if the length of the seq1 and the seq2 are diffenrent**

In [79]:
# making two array with diffennt length
seq1 = randint(6, size=(5,))
seq2 = randint(6, size=(4,))

# now we have two sequence of different size
print(seq1)
print(seq2)

[0 2 0 5 2]
[0 5 0 2]


In [80]:
# using the tow sequence have different length

array[seq1 , seq2]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (5,) (4,) 

See, we cannot do indexing with multi-dimensioanl array which are having the different length. This will gives us a IndexError.

***
`Conclusion:`
Indexing an array with other arrays or array like sequence:
* It must be iterable object.
* It must not contains the value which is out of index number.
* It must contains only interger
* The length of the array like sequence can have values in N-dimensions  
* Slicing like seq1:seq2 are not permettied in a single dimension
* Slicing and index array combination are permitted.
* Multi dimensional index array are also permitted to make a new array by using the elements of the array.
* Multi dimensional index array of diffenent length are not permitted.

***
---

## Boolean or Mask index array:

Boolean or mask index array is different from the genearal index array, general index array contains the interger value as the index number but the boolean or mask index array contains only Boolean values like `True and False`. 

Boolean array Can be generated with the help of various technique or it can be given as munual to the array:

A Boolena array looks like this:
```ruby
array([[False,  True, False,  True, False, False],
       [ True,  True,  True, False,  True,  True],
       [False,  True, False,  True, False,  True],
       [ True, False, False, False,  True,  True],
       [False,  True, False,  True, False, False],
       [False, False,  True,  True, False,  True]])
```

A boolean array contains both `True` and the `False` values in the index array. but the resulted array will be short to the boolean array because in this it will only select those element which are having `True` at their corresponding index location in the original array.

We can see it by using an example: we have 1d index array and also having a array which is to be indexed.


In [86]:
# array to be indexed named as test
test = randint(10, size=(10,))
test

array([9, 0, 6, 6, 5, 8, 8, 5, 9, 4])

In [89]:
# boolean array with randomness
# making a boolean array with numpy.random.choice() function
choose = [True, False]
bool_array = choice(choose, size=(10, ))
bool_array

array([ True, False, False, False,  True,  True,  True, False, False,
       False])

Now we have both 1d array and the boolean array now we will see that how it works when we pass this bool_array (index_array) into the array.

In [92]:
print("Our original array:\n",test)
print("\nboolean array:\n",bool_array)
print("\nindexd array:\n",test[bool_array])


Our original array:
 [9 0 6 6 5 8 8 5 9 4]

boolean array:
 [ True False False False  True  True  True False False False]

indexd array:
 [9 5 8 8]


As you can see that our indexed array shape is different, this is like filterring of the elements which do meet the filter conditions we often use this method to filter things in the pandas dataframe and series during the data analysing. 

`Note:` The shape and the size of the output array depends on the boolean array, if the boolean array has the 2D index array then it can give us the 2D indexed array.

Let's Work on the 2d array:

In [93]:
# Our oringinal array is 
array

array([[85, 10, 91, 31, 56, 51],
       [21, 30, 20, 94, 45, 37],
       [55, 24, 52, 38, 81, 11],
       [ 6, 89, 92, 65, 39, 19],
       [62, 45, 57, 25, 94, 88],
       [84, 62,  9, 26, 57, 47]])

In [102]:
# Making a 2d boolen array wiht some making
# masking can be done with some logican operantion b/w the array and some condition
# like array > 24 ; it means the select all the element which are greater than the 24 inside the  array.

# This operation returns a boolean array with True and False values

bool_array = array > 50
bool_array

array([[ True, False,  True, False,  True,  True],
       [False, False, False,  True, False, False],
       [ True, False,  True, False,  True, False],
       [False,  True,  True,  True, False, False],
       [ True, False,  True, False,  True,  True],
       [ True,  True, False, False,  True, False]])

In [103]:
print("Shape of the bool array: ", bool_array.shape )
print("Size of the bool array: ",bool_array.size)

Shape of the bool array:  (6, 6)
Size of the bool array:  36


We have the size and shape of the boolen array now we will do the indexing with the boolean array:

In [104]:
array[bool_array]

array([85, 91, 56, 51, 94, 55, 52, 81, 89, 92, 65, 62, 57, 94, 88, 84, 62,
       57])

As you can see that we have got our result according to the bool_array. bool_array contains True to corresponding location where element is greater then the 50 into the array and returns it during the indexing. Since boolean indexing is different from the general indexing , it is more like filtering something from the array with some logic in this we dont need to know the index value of that particular values. 

`Note:` The esult will be multidimensional if array has more dimension then boolean array. 

**Example 1**

In [106]:
# Suppose that we have a 1d array in which we need to match the size of that dimension in which we are indexing it.

# boolean array accoriding to the row indexing
# Since our array has 6 x 6 shape we dont need to worry about the shape of the boolean array.
choose = [True, False]
bool_array = choice(choose, size=(6, ))
bool_array

array([ True,  True,  True, False, False, False])

In [107]:
array[bool_array]

array([[85, 10, 91, 31, 56, 51],
       [21, 30, 20, 94, 45, 37],
       [55, 24, 52, 38, 81, 11]])

As You can see that now we have a 2d indexed array after passing the boolen array into the array. Because the dimension of the boolean array is less than the array. 

In this case the boolean array do not have the True and False vlaues corresponding to the array items instead this time they are corresponding to the rows of the array it is similar to the 1d index array which has the interger values less than the index range of the array.

**Example 2:**  Passing boolean index array at the place of column of the array:

In [108]:
# array[rows, columns]
array[:,bool_array]

array([[85, 10, 91],
       [21, 30, 20],
       [55, 24, 52],
       [ 6, 89, 92],
       [62, 45, 57],
       [84, 62,  9]])

Here `:` represents that select all the available row of the array.

**Example 3:** Indexing of Non-square array.

For that we need to create a new array, Let's Create an random array with a shape of (5,6).

In [109]:
# creating a random non-square array
array2 = randint(100, size=(5,6))
array2

array([[64, 89, 47, 58, 97, 23],
       [23, 20, 66, 23, 13, 80],
       [61, 47, 39, 53, 78,  4],
       [ 6, 98, 13, 88,  6, 72],
       [29,  2,  0, 32, 47, 79]])

In [110]:
bool_array

array([ True,  True,  True, False, False, False])

Now we need two different bool_array which matches the size of the both rows and columns, In this case we need one bool_array for row and one bool_array for the column which matches size of the row and columns.

In [111]:
# since our first bool_array alreay meets the requirment for the size of rows so we need the array for the column size

choose = [True, False]
bool_array2 = choice(choose, size=(5, )) # size is 5 for the columns
bool_array2

array([ True, False, False,  True,  True])

Now we have two different boolean arrays one for the rows and another for the columns.

In [112]:
print("Boolean array for the rows of the array: ",bool_array)
print("Boolean array for the columns of the array: ", bool_array2)

Boolean array for the rows of the array:  [ True  True  True False False False]
Boolean array for the columns of the array:  [ True False False  True  True]


In [114]:
# indexing using the row of the array2
array2[bool_array2]

array([[64, 89, 47, 58, 97, 23],
       [ 6, 98, 13, 88,  6, 72],
       [29,  2,  0, 32, 47, 79]])

In [115]:
# indexing using the column of the array2
array[:, bool_array]

array([[85, 10, 91],
       [21, 30, 20],
       [55, 24, 52],
       [ 6, 89, 92],
       [62, 45, 57],
       [84, 62,  9]])

As you can see that we need different size of the boolean index array for the non-square 2d array. Otherwise it will raise the IndexError.
***
***

## Structural Indexing tools

`Structural indexing:` To facilitate easy matching of array shapes with expresions and in assingnments , the np.newaxis  objects can be used wthin array indeces to add new dimnsions with a size of 1.

In [125]:
# creating a new array 
temp = randint(20, size=(4,3))
print(temp)
print("\n Shape of the array: ",temp.shape)

[[11  3 15]
 [ 4  2 14]
 [12  7 19]
 [12 13  0]]

 Shape of the array:  (4, 3)


Now we have a new temp array, we will add a new axis into the temp array.

In [122]:
temp[:,np.newaxis,:]

array([[[15,  7, 16]],

       [[ 9, 17, 16]],

       [[ 6, 18,  7]],

       [[19,  6, 18]]])

In [123]:
temp[:,np.newaxis,:].shape

(4, 1, 3)

Now, as you can see that we have added a new axis.

`Note:` Notice that there are no new elements in the array, just that the dimensionality is incereased. This can be handy to combine two arrats in a wat that otherwie would require explicitly reshaping operations.

***Adding two arrays***

In [126]:
temp

array([[11,  3, 15],
       [ 4,  2, 14],
       [12,  7, 19],
       [12, 13,  0]])

In [129]:
# we already have one temp array we need one more temp array to perorm this task
temp2 = randint(20, size=(4,1,3))
print(temp2)
print("shape of the temp2 array: ", temp2.shape)

[[[ 6  3 12]]

 [[16  2 18]]

 [[ 4  9 17]]

 [[ 5 17  8]]]
shape of the temp2 array:  (4, 1, 3)


In [131]:
# adding the temp one and temp2
temp.shape

(4, 3)

In [132]:
temp + temp2

array([[[17,  6, 27],
        [10,  5, 26],
        [18, 10, 31],
        [18, 16, 12]],

       [[27,  5, 33],
        [20,  4, 32],
        [28,  9, 37],
        [28, 15, 18]],

       [[15, 12, 32],
        [ 8, 11, 31],
        [16, 16, 36],
        [16, 22, 17]],

       [[16, 20, 23],
        [ 9, 19, 22],
        [17, 24, 27],
        [17, 30,  8]]])

In [133]:
(temp + temp2).shape

(4, 4, 3)

***Combining the arrays***

In [135]:
# let's create an 1d array for that 
temp = arange(5)
temp

array([0, 1, 2, 3, 4])

In [136]:
# lets create a new axis at the row and the columns places
print("adding a newaxis at row:\n ", temp[np.newaxis,:])
print("\nadding a newaxis at column:\n ",temp[:,np.newaxis])

adding a newaxis at row:
  [[0 1 2 3 4]]

adding a newaxis at column:
  [[0]
 [1]
 [2]
 [3]
 [4]]


In [137]:
# combining the new temp array after the adding newaxis 
temp[np.newaxis,: ] + temp[:, np.newaxis]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

**Ellipsis syntax:** ellopssis syntax maybe used to indicate selecting in full any remaining unspecified dimensions.

For example:

In [138]:
temp = np.arange(81)
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [140]:
# now we will reshape it 
temp.reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

Now you can see that we have a new temp which has new shape. 

In [144]:
temp = temp.reshape(3,3,3,3)
temp.shape

(3, 3, 3, 3)

In [149]:
# Ellipsis syntax to slice the array
temp[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

The above syntax is equivalent to:

In [150]:
temp[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [152]:
# or we can also use different dimensions in slicing 
temp[...,2]

array([[[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]],

       [[29, 32, 35],
        [38, 41, 44],
        [47, 50, 53]],

       [[56, 59, 62],
        [65, 68, 71],
        [74, 77, 80]]])

The ellipsis syntax `...` shows that we are counting all the dimension and all the elements corresponding to the selected dimension. the syntax `...` select the all dimensions which are not specified in the contigous manner.

suppose that we have an array of 6 dimension then ellipsis syntax `...` will be used to select contigous dimensions.

In [153]:
temp = np.arange(64)
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]


In [154]:
# changing the shape of the array
temp = temp.reshape(2,2,2,2,2,2)
print("shape of the array: ",temp.shape)

shape of the array:  (2, 2, 2, 2, 2, 2)


In [155]:
temp

array([[[[[[ 0,  1],
           [ 2,  3]],

          [[ 4,  5],
           [ 6,  7]]],


         [[[ 8,  9],
           [10, 11]],

          [[12, 13],
           [14, 15]]]],



        [[[[16, 17],
           [18, 19]],

          [[20, 21],
           [22, 23]]],


         [[[24, 25],
           [26, 27]],

          [[28, 29],
           [30, 31]]]]],




       [[[[[32, 33],
           [34, 35]],

          [[36, 37],
           [38, 39]]],


         [[[40, 41],
           [42, 43]],

          [[44, 45],
           [46, 47]]]],



        [[[[48, 49],
           [50, 51]],

          [[52, 53],
           [54, 55]]],


         [[[56, 57],
           [58, 59]],

          [[60, 61],
           [62, 63]]]]]])

**Example 1**

In [156]:
# ellipsis syntax
# Now we will apply the silcing on the 4th and 5th dimension and the rest of it will be selected by the ellipsis method
temp[...,0,1] 

array([[[[ 1,  5],
         [ 9, 13]],

        [[17, 21],
         [25, 29]]],


       [[[33, 37],
         [41, 45]],

        [[49, 53],
         [57, 61]]]])

**Example 2**

In [157]:
temp[...,0,1,:]

array([[[[ 2,  3],
         [10, 11]],

        [[18, 19],
         [26, 27]]],


       [[[34, 35],
         [42, 43]],

        [[50, 51],
         [58, 59]]]])

We can see that in both example the result is different because in:

Example 1: first we used the ellipsis syntax, by using this we counts all the dimensions upto the manual specification. in this example we have specified some indexing in two dimension. Since `...` syntax count all the contigous dimension up to the manual specification like this , we have counted all the first 4 dimension becaues we only specifed 2 manual dimension in the indexing.

Note: if we would give only one dimension manually then the `...` syntax would taken the first 5 dimension itself. This confusion is cleared from the example 2.

Example 2: in this we have mentioned last three dimensions manually for the indexing and by using this with `...` syntax, ellipsis syntax counts the remaining all off the dimenisons itself.
***
***

## Assigning values to indexed arrays:

Assigning is similar to the assigning some values into the some object like `a =2 `. in this we have assigned '2' in an object 'a'. but there are some additional feature and constraint of the assigning of arrays:

* ine can select a subset of an array to assign to using a single index, slices, and index and mask arrays. 
* The value being assigned to the indexed array must be shpae consistent (the same shape or broadcastable to the shpae the index produces).

In [158]:
temp = arange(15)
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [160]:
# assign 0 to all the values from 5 to 10 position.
temp[5:11] = 0  # 11 is for the 10+1 becuse 11 is not inclusive 
temp

array([ 0,  1,  2,  3,  4,  0,  0,  0,  0,  0,  0, 11, 12, 13, 14])

As you can see that we have assigned some zeros to the array.

##### Case 1: Assigning values to the Nd-arrays:

In [162]:
# createing a 2d array
temp = randint(50, size=(4,3))
temp

array([[ 2, 25, 13],
       [39, 43, 45],
       [46, 38, 29],
       [23, 16, 19]])

 now assigning 0 at the place of 43 and 38.
 
 Sicne this location are in same column so we can do it using the slicing:
 
 1. Select those rows in which 43 and 48 are present 
 2. Select the column of the corresponding values

In [165]:
# rows -------------> 2nd and 3rd
# columns ----------> 2nd 
temp[1:3, 1] = 0
temp

array([[ 2, 25, 13],
       [39,  0, 45],
       [46,  0, 29],
       [23, 16, 19]])

As you can see that we have assingned values in the indexed arrays