# Introduction

There are 5 general mechanisms for creating arrays:

1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

This section will not cover means of replicating, joining, or otherwise expanding or mutating existing arrays. Nor will it cover creating object arrays or structured arrays. Both of those are covered in their own sections.

# Numpy Data Science basic operations.

In this tutorial we will perform some of the basic operation of the numpy array such as..

* Creating array
* Getting the array size
* accessing the array elements 
* slicing the array

Importing the numpy module

In [2]:
import numpy as np

# 1. Creating an array 
In this section we will see the creation of the array and what are the ways to create the array using the numpy mdule. first of all we will see the `numpy.array()` module which can be used to create an nd-array.

```ruby
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```
For documentation see the below like.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html?highlight=numpy%20array#numpy.array">numpy.array()</a>

First of all we will see that how we create an arrya object with the help of the `numpy.array()` and the list.

Suppose that we have a list: 
```ruby
List: [1,2,3,4,5,6] 
```
Now we will pass that list into the numpy.array() in object parameter.
```ruby
object: # object is a variable or instance which holds the values or the data strucuture which need to be converted into the numpy array.

dtype: # dtype will defines the data type of the array which we are creating, you should check the tutorial on Numpy data types.
```

For now we will only see these two parameters of the.

In [3]:
# creating the numpy array with numpy.array()
List = [1,2,3,4,5,6] 
array1 = np.array(List,int) # here first parameter is object and the second one is for the datatype of the numpy object

print(array1)

[1 2 3 4 5 6]


In [4]:
array1

array([1, 2, 3, 4, 5, 6])

## Creating multi dimensional array

Suppose that we have two list or a nested list with two sub list then if we pass thid nested list into the array object we can create the nd- array.

```ruby
List1 : [1,2,3,4,5,6,7,8,9]
List2 : [1,2,3,4,5,6,7,8,9]
List3 : [1,2,3,4,5,6,7,8,9]
```
Now we have three list, we will use them to create the nd-array

In [10]:
List1 = [1,2,3,4,5,6,7,8,9]
List2 = [1,2,3,4,5,6,7,8,9]
List3 = [1,2,3,4,5,6,7,8,9]

# now we have three list list1, list2, list3 
# making a 2d array

array_2d = np.array([List1, List2], int)

# pritnting the array 
print("this is my 2d array: \n", array_2d)

array_2d = np.array([List1,List2,List3])

# printing the array
print("\nthis is my another 2d array: \n", array_2d)

this is my 2d array: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]

this is my another 2d array: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


As you can see that we have made a numpy array with the help of the numpy.array() and a list. We can also use the tuple insted of the list.

For now we will not see the 3d array we will make a seprate array on the 3d array.

Now we will see some inbuilt function to create the array.

***

## Creating array with some inbuilt function of the numpy

Numpy module is a wast module operation on the array or multi dimensional array in which we have some inbult funciton which can create a particular type of array. LIke:

* zeros()
* ones()
* empty()
* arange()
* linspace()
* indices()
* empty_like()
* zeros_like()
* ones_like()
* em