## First of all import the numpy module

In [1]:
import numpy as np

# numpy.random() Module

In this section we will work on the numpy.random module and its implimantation in the data science

Most common funcion of the random modules are.

* numpy.random.random()
* numpy.random.rand()
* numpy.random.randn()
* numpy.random.randint()
* numpy.random.random_sample()
* numpy.random.random_integers()
* numpy.random.choice()

### 1. numpy.random.random()
```ruby
random(size=None)
```
Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.


* First of all we will see that how random works. Since random only takes one argument and that argument is the size of the array.


In [5]:
# 1. random function of the random class in numpy.

np.random.random((4,2))

array([[0.72952913, 0.42908422],
       [0.47079735, 0.243812  ],
       [0.393077  , 0.99590081],
       [0.32099304, 0.97212375]])

Random function of the random class does not have any other argument so we are done with the `np.random.random()` function.
***

## 2. numpy.random.rand()
```ruby
rand(d0, d1, ..., dn)
```
Random values in a given shape.

This function takes the n parameters as shape of the output or desired result in which all the argument are the shape values. The output will be according to the given shape.

**creating an array having a shape of (3,2,1)**

In [7]:
# 2. rand function in the random class.

np.random.rand(3,2,1)

array([[[0.55684481],
        [0.49152949]],

       [[0.63178713],
        [0.16742483]],

       [[0.03846722],
        [0.68848692]]])

**creating an array having a shape of (5,4,3,2)** 

In [11]:
# shape = (5,4,3,2)

rand_array = np.random.rand(5,4,3,2)
print(rand_array)

[[[[0.63890261 0.07504637]
   [0.66434503 0.05465705]
   [0.38981777 0.54450993]]

  [[0.94618289 0.97252164]
   [0.93946935 0.90217431]
   [0.76110369 0.24627802]]

  [[0.85494758 0.76054344]
   [0.05901945 0.3087478 ]
   [0.9367858  0.02845257]]

  [[0.35563543 0.88613542]
   [0.46544782 0.96180228]
   [0.51596369 0.18883559]]]


 [[[0.93917668 0.3252935 ]
   [0.67805158 0.51468751]
   [0.02201133 0.88526434]]

  [[0.63140171 0.82079545]
   [0.03346929 0.51380735]
   [0.42626078 0.66365645]]

  [[0.75064095 0.33721963]
   [0.75514139 0.47260839]
   [0.98114615 0.33688789]]

  [[0.20953854 0.62241718]
   [0.13714061 0.63788332]
   [0.56770895 0.07137547]]]


 [[[0.05329385 0.81839523]
   [0.15171122 0.77114964]
   [0.63359429 0.590501  ]]

  [[0.51534257 0.89221415]
   [0.34459237 0.56245487]
   [0.88104408 0.97649887]]

  [[0.37489805 0.2032884 ]
   [0.81492133 0.5542299 ]
   [0.86175628 0.61191274]]

  [[0.93076259 0.32200435]
   [0.86417596 0.73668626]
   [0.59513072 0.9522764 ]]]


As you can see that our result is very long and very large, so we can see that our `np.random.rand()` function does not takes  any other parameters other than shape of the desired array. 

if you want to check the shape and dimension of the array then we can do it with the help of the ndarray property attributes.

In [12]:
# to check the shape we use ndarray.shape
print("Shape of the above rand array: ",rand_array.shape)

# to check the dimension we need to use ndarray.ndim
print("Dimension of the above rand array: ",rand_array.ndim)

Shape of the above rand array:  (5, 4, 3, 2)
Dimension of the above rand array:  4


As we given we have got our result now we should move on to the `randn` function. 

## 3. numpy.random.randn()
```ruby
numpy.random.randn(d0, d1, ..., dn)
```
Return a sample (or samples) from the "standard normal" distribution.

This function generates N-dimensional array which contains both negative and positive values. This method use the gaussion distribution method to generate the uniform random numbers.

In [14]:
np.random.randn(4,3,2)

array([[[ 0.68007514, -0.08385047],
        [ 1.57425745,  1.06391927],
        [-0.57639136, -0.8983189 ]],

       [[-2.16935359,  2.4493302 ],
        [ 1.62496659, -0.46989534],
        [ 0.63610703, -0.64561476]],

       [[ 0.93314148,  0.37388158],
        [ 0.44468941,  0.36993568],
        [ 0.10303313, -0.80758421]],

       [[-2.20014653, -0.64536125],
        [-0.69997252, -1.66649297],
        [-1.31251828,  0.48167002]]])

***

## numpy.random.randint()
```ruby
randint(low, high=None, size=None, dtype=int)
```
Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

In [ ]:
np.random.randint()