# Introduction

There are 5 general mechanisms for creating arrays:

1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

This section will not cover means of replicating, joining, or otherwise expanding or mutating existing arrays. Nor will it cover creating object arrays or structured arrays. Both of those are covered in their own sections.

# Numpy Data Science basic operations.

In this tutorial we will perform some of the basic operation of the numpy array such as..

* Creating array
* Getting the array size
* accessing the array elements 
* slicing the array

Importing the numpy module

In [1]:
import numpy as np

# 1. Creating an array 
In this section we will see the creation of the array and what are the ways to create the array using the numpy mdule. first of all we will see the `numpy.array()` module which can be used to create an nd-array.

```ruby
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```
For documentation see the below like.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html?highlight=numpy%20array#numpy.array">numpy.array()</a>

First of all we will see that how we create an arrya object with the help of the `numpy.array()` and the list.

Suppose that we have a list: 
```ruby
List: [1,2,3,4,5,6] 
```
Now we will pass that list into the numpy.array() in object parameter.
```ruby
object: # object is a variable or instance which holds the values or the data strucuture which need to be converted into the numpy array.

dtype: # dtype will defines the data type of the array which we are creating, you should check the tutorial on Numpy data types.
```

For now we will only see these two parameters of the.

In [3]:
# creating the numpy array with numpy.array()
List = [1,2,3,4,5,6] 
array1 = np.array(List,int) # here first parameter is object and the second one is for the datatype of the numpy object

print(array1)

[1 2 3 4 5 6]


In [4]:
array1

array([1, 2, 3, 4, 5, 6])

## Creating multi dimensional array

Suppose that we have two list or a nested list with two sub list then if we pass thid nested list into the array object we can create the nd- array.

```ruby
List1 : [1,2,3,4,5,6,7,8,9]
List2 : [1,2,3,4,5,6,7,8,9]
List3 : [1,2,3,4,5,6,7,8,9]
```
Now we have three list, we will use them to create the nd-array

In [10]:
List1 = [1,2,3,4,5,6,7,8,9]
List2 = [1,2,3,4,5,6,7,8,9]
List3 = [1,2,3,4,5,6,7,8,9]

# now we have three list list1, list2, list3 
# making a 2d array

array_2d = np.array([List1, List2], int)

# pritnting the array 
print("this is my 2d array: \n", array_2d)

array_2d = np.array([List1,List2,List3])

# printing the array
print("\nthis is my another 2d array: \n", array_2d)

this is my 2d array: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]

this is my another 2d array: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


As you can see that we have made a numpy array with the help of the numpy.array() and a list. We can also use the tuple insted of the list.

For now we will not see the 3d array we will make a seprate array on the 3d array.

Now we will see some inbuilt function to create the array.

***

## Creating array with some inbuilt function of the numpy

Numpy module is a wast module operation on the array or multi dimensional array in which we have some inbult funciton which can create a particular type of array. LIke:

* zeros()
* ones()
* empty()
* full()
* empty_like()
* zeros_like()
* ones_like()
* full_like()
* arange()
* linspace()
* indices()

## Zeros array

we can make the zeros array with a shape.

```ruby
zeros(shape, dtype=float, order='C', *, like=None)
```
Return a new array of given shape and type, filled with zeros.
 
 You can see the additional reference of the numpy.zeros form the link.
<a href="https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=numpy%20zeros#numpy.zeros">numpy.zeros()</a>

In [14]:
# here also we will see the most commonly used parameters 
# shape: this will define the shape of the array and it takes a list or a tuple as input
# dtype: this will define the data type of the array.

# 1. dtype: int    and  shape:(2,2)
zeros_array = np.zeros((2,2), dtype=int)

print("This is the int type (2,2) array:\n",zeros_array)

# 1. dtype: float    and  shape:(3,2)
zeros_array = np.zeros((3,2), dtype=float)
print("\nthis is the float type (3,2) array:\n",zeros_array)

This is the int type (2,2) array:
 [[0 0]
 [0 0]]

this is the float type (3,2) array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


Here array is created in this format ----> (R,C,P)
* R: Rows
* C: Columns
* P: Plane

## Ones array

Now we will see ones array and the syntax is:
```ruby
 np.ones(shape, dtype=None, order='C', *, like=None)
```
Return a new array of given shape and type, filled with ones.



In [15]:
# now we will se ones array with int and float data type

# dtype: int     and   shape: (2,2)
ones_array = np.ones((2,2),int)
print("This is the ones array of int type and a shape of (2,2) :\n", ones_array)

# dtype: int     and   shape: (3,2)
ones_array = np.ones((3,2),float)
print("\nThis is the ones array of float type and a shape of (3,2) :\n", ones_array)

This is the ones array of int type and a shape of (2,2) :
 [[1 1]
 [1 1]]

This is the ones array of float type and a shape of (3,2) :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
np.empty()

## Empty array
Now we will see the empty array

```ruby
np.empty(shape, dtype=float, order='C', *, like=None)
```
Return a new array of given shape and type, without initializing entries.

For furthur detail see this: 
<a href="https://numpy.org/doc/stable/reference/generated/numpy.empty.html?highlight=numpy%20empty#numpy.empty">numpy.empty() </a>
    

In [33]:
# now we will see the empty array of n-shape

# dtype: int    and          shape:(2,2)
empty_array = np.empty((2,3), int)
print("This is the empty array of int type and a shape of (2,2) :\n", empty_array)


# dtype:float    and          shape:(2,4)
empty_array = np.empty((2,4), float)
print("\nThis is the empty array of float type and a shape of (2,3) :\n", empty_array)

This is the empty array of int type and a shape of (2,2) :
 [[-1997275216         453           0]
 [          0           1  2098768637]]

This is the empty array of float type and a shape of (2,3) :
 [[0.00e+000 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 4.07e-321 0.00e+000 0.00e+000]]


`Note:` empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

## Full array
Now we will see the full array, creatinf full arry is different form the above defined arrays.

```ruby
 np.full(shape, fill_value, dtype=None, order='C', *, like=None)
```
Return a new array of given shape and type, filled with `fill_value`.

See the full documentation on the `numpy.full()` array: 
<a href="https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full">numpy.full()</a>


In [37]:
# now we will see the full array in the numpy module 
# Since this full array is different from the other whcih is defined above so we will see in details

# the main thing which is different in this is that fill_values.
# so we will do some work on the fill_values.

# dtype: int       and          shape:(2,2)
full_array = np.full((2,2),int)
print("This is the full array of int type and the shape is (2,2) : \n",full_array)

# dtype: float       and          shape:(2,4)
full_array = np.full((2,4), float)
print("\nThis is the full array of float type and the shape is (2,4) : \n",full_array)

This is the full array of int type and the shape is (2,2) : 
 [[<class 'int'> <class 'int'>]
 [<class 'int'> <class 'int'>]]

This is the full array of float type and the shape is (2,4) : 
 [[<class 'float'> <class 'float'> <class 'float'> <class 'float'>]
 [<class 'float'> <class 'float'> <class 'float'> <class 'float'>]]


Now we have done the same thing which have made in previous all of the array but in this case we can see that there is no values in this. Because in this we need to provide the values in the `fill_values` parameters.

So, let's do some test with some values.

#  Non-square shape full array

## Case 1: Only passing a single value to fill_vlaue 

In [38]:
# in this we will provide only one value 

# dtype : int       shape: (2,3)      fill_value:[1]
# carefull: here the second parameter is "fill_values" so we need to pass some values in that
np.full((2,3),[1],int )

array([[1, 1, 1],
       [1, 1, 1]])

Note: we need to see the above output. in this result we have made an array a shape of (2,2) and only passed [1].

In this case 1 will be filled to all allocated location. 

***

## Case 2: Passing two values to fill_vlaue

In [41]:
# in this we will provide two value 

# dtype : int       shape: (2,3)      fill_value:[1,2]
# carefull: here the second parameter is "fill_values" so we need to pass some values in that
np.full((2,3),[1,2],int )

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

`Note:` We can see that when we try to pass value which are not equal to the column of the shape of the array. Then it will show the ValueError message.
like,
```ruby
List: [1,2] or [1,2,3,4]
```

**Now we will pass the values equal to the column of the array**

In [46]:
# in this we will provide three value 

# dtype : int       shape: (2,3)      fill_value:[1,2,3]
# Carefull: here the shape of the array is (2,3)
# then the column values should be 3.

np.full((2,3),[1,2,3],int )

array([[1, 2, 3],
       [1, 2, 3]])

Now we can see the we have created the an array with a shape of (2,3) and fill_values:[1,2,3].

But as you can notice that these values are repeting in each row. So if we dont want to repeat the values in the row then what?

**Now we will give the values equal to the rows and columns**

In [47]:
# in this we will provide two list containg the equal value 

# dtype : int       shape: (2,3)      fill_value:[1,2,3],[4, 5,6]
# Carefull: here the shape of the array is (2,3)
# then the column values should be 3.
# and rows are 2.

np.full((2,3),[[1,2,3],[4,5,6]],int )

array([[1, 2, 3],
       [4, 5, 6]])

Now as you can see that we have eleminate the problem of repetation of the values by providing the values equl to the rows and columns. 

`Note:` Be carefull when passing the *fill_values*. it should be equal to the number of columns or both columns and rows.

**Now we will double the shpae of the previous one**

In [50]:
# in this we will increase the colulmns by twice but the input will be same as was in previous one.

# dtype : int       shape: (2,3)      fill_value:[1,2,3],[4, 5,6]
# Carefull: here the shape of the array is (2,3)
# then the column values should be 3.
# and rows are 2.

np.full((2,6),[[1,2,3],[4,5,6]],int )

ValueError: could not broadcast input array from shape (2,3) into shape (2,6)

`Error:` As can see that we have *ValueError* because we didn't pass the values in the right shape. So to solve this problem we have three option.

* We can pass a single value which will fill all the (i,j) loaction
* We can pass a single list which will fill the all row with same values.
* We can pass an array or array_like object with the same shape of the current one. Like if the shape of the current full() array is (4,6) then we can pass an array with this shape.

But for now we will only do the first two method.

#### Method 1

In [51]:
np.full((2,6),[1],int )

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### Method 2

In [53]:
np.full((2,6),[1,2,3,4,5,6],int )

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [54]:
np.full((6,2),[1,2],int )

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

`Note:` As we can see that we have resolved the ValueError problem in this by using the first two methods.

We didn't use the third method because if we want to fill all the values by ourself then we should use the *numpy.array()* funtion not this *numpy.full()* funtion to create an array which is having the all vlaues defined by user.

**Now we will see the like version of zeros, ones, empty and full arrays**

These funciton are similar to the normal function of the numpy module.  

* zeros_like
* ones_like
* empty_like
* full_like

For furthur reading on them see this:
* <a href="zeros_link">zeros_like()</a>
* <a href="zeros_link">ones_like()</a>
* <a href="zeros_link">empty_like()</a>
* <a href="zeros_link">full_like()</a>

## zeros_like array
```ruby
np.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
```
Return an array of zeros with the same shape and type as a given array.

`a:` a is the list or array like structure whcih is the input


#### Case 1: if we pass 1d array.

In [58]:
# we will give 'a' as a 1d array with a random shape

a = [1,2,3]
np.zeros_like(a)

array([0, 0, 0])

#### Case2: if we pass 2d array.

In [61]:
# Now we will give 'a' as a 2d array with a random shape

a = [[1,2,3],[4,5,3]]
np.zeros_like(a, dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

#### Case 3: if we pass 3d array.

In [64]:
# Now we will pass 'a' as a 3d array with a random shape
 
a = [    [[1,2], [3,4]],
     
         [[5,6], [7,8]],
     
         [[9,10],[11,12]]
]

np.zeros_like(a, dtype=int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

**difference b/w the `np.zeros` and `np.zeros_like`**

Now we will use both np.zeros and np.zeros_like funtion
1. Zeros method

In [67]:
# Now we will use the zeros method 
np.zeros((3,2,4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

`Note:` In zeros function

* We need to give the shape of the desired array.

In [70]:
# NOw we will use the zeros_like function
a = a = [[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]]
np.zeros_like(a, dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

`Note:` In zeros_like function
* We need to give the an array and we will get an array of zeros which has the same shape of input array.

**Conclusion**
* In zeros we need to give the array shape and gets the array with a given shape.
* In zeros_like we need to give an array and gets the array with a shape  same as the shape of the input array.

## ones_like array

`Note:` Since ones and ones_like are similar to the zeros and zeros_like respectively. So we will perfrom the 3d array.

In [83]:
# Ones array
print("shape:",np.ones(shape=[4,3,2] , dtype=int).shape)
np.ones(shape=[4,3,2] , dtype=int)

shape: (4, 3, 2)


array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

shape: (4, 3, 2)


In [84]:
# ones_like array

# Now we will pass 'a' as a 3d array with a random shape
 
a = [    [[1,2], [3,4]],
     
         [[5,6], [7,8]],
     
         [[9,10],[11,12]],
     
         [[13,14],[15,16]]
]
print("shape:",np.ones_like(a , dtype=int).shape)
np.ones_like(a , dtype=int)

shape: (4, 2, 2)


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

**Conclusion**
* In ones we need to give the array shape and gets the array with a given shape.
* In ones_like we need to give an array and gets the array with a shape  same as the shape of the input array.

## empty_like array

In [89]:
# we are making a empty array of a shape:[4,2,2]
print("shape:",np.ones_like(a , dtype=int).shape)
np.empty([4,2,2])

shape: (4, 2, 2)


array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.33511018e-306]],

       [[8.34441742e-308, 1.78022342e-306],
        [6.23058028e-307, 9.79107872e-307]],

       [[6.89807188e-307, 7.56594375e-307],
        [6.23060065e-307, 1.78021527e-306]],

       [[8.34454050e-308, 1.11261027e-306],
        [1.15706896e-306, 1.33512173e-306]]])

In [90]:
# we are making a empty_like array of a shape:[4,2,2]

# this is the input array for the empty_like array which is float in dtype
a = [[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.33511018e-306]],

       [[8.34441742e-308, 1.78022342e-306],
        [6.23058028e-307, 9.79107872e-307]],

       [[6.89807188e-307, 7.56594375e-307],
        [6.23060065e-307, 1.78021527e-306]],

       [[8.34454050e-308, 1.11261027e-306],
        [1.15706896e-306, 1.33512173e-306]]]

# the shape of this a is (4,2,2)
print("shape:",np.empty_like(a, dtype=int).shape)

# now we will make an int dtype array from the input float dtype array. 
np.empty_like(a, dtype=int)

shape: (4, 2, 2)


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

**Conclusion**
* In empty we need to give the array shape and gets the array with a given shape.
* In empty_like we need to give an array and gets the array with a shape  same as the shape of the input array.

## full_like array

In [97]:
# here fv variable represent the fill_value parameter values in the full and full_like array
fv = [[1,2,3]]

print("shape: ",np.full((4,3),fv ,dtype=int).shape)
np.full((4,3),fv ,dtype=int)

shape:  (4, 3)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [99]:
a = [[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]

# here a is the input array which will help to get the shape of the desired array.

fv = [[-1,0,-1]]
# after getting the shape from the above array we will fill fv values in that array

print("shape: ",np.full_like(a,fv ,dtype=int).shape)

#
np.full_like(a,fv, dtype=int)

shape:  (4, 3)


array([[-1,  0, -1],
       [-1,  0, -1],
       [-1,  0, -1],
       [-1,  0, -1]])

**Over All Conclusion**
We have seen that normal version of zeros, ones, empty and full need a shape of the desired array to create the array but in the *'_like'*  version of these function we need to give an array or an array like object such as list. 

***
---

***Now we will do the rest of the function***
* arange()
* linspace()
* indices()
* ogrid()
* mgrid()

## arange() array
Now we will do some operation on the arange funtion
`arange:` arange function is very similar to the `range()` function. `range()` function generates the a series of number with a  step (constant diffenrene).

```ruby
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
```
Return evenly spaced values within a given interval.

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). 

For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

For furthur reading see this:
<a href="https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange">numpy.arange()</a>

**Like**

In [106]:
for i in range(1,111,10):
    print(i, end=" ")

1 11 21 31 41 51 61 71 81 91 101 

`Note`: Here we have a series from 1 to 111 with a step or a constant difference b/w each number. Like this arange function also generate the array containg a series like range function.

In [108]:
# now we will make a arange array

np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [109]:
np.arange(100,500,10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490])

As you can see that `arange()` function return a ndarray.

***Now we will use the `like` parameter in the arange function***

`like:` like is an array or array like object in which we pass an array or array like object like list then it will generate the array having 

In [114]:
alike = [[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]
alike = np.ones_like(alike)
# here alike is the value of the like parameter in the arange function
print(alike)
np.arange(1,100,like=alike)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

`Note:` **The task of the creation of arange array with like parameter is not completed.**

***

## linspace() array

When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use` numpy.linspace `for these cases.

```ruby
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].


For furthur reading see this:
<a href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace" >numpy.linspace()</a>

In [119]:
# As we can see in the syntex of the numpy.linspace all the values are given except start and stop.
# start: this is the starting value of the series
# stop: this ts the ending value of the series.

linspace_array = np.linspace(1,20)
print(linspace_array)

print("\nlength of the linspace array: ",len(linspace_array)) 

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]

length of the linspace array:  50


As you can see that by default `linspace` generates the 50 values which are evenly spaced. 

Now if we change the `linspace(num=' 10' )` parameter to other value like 10 then it will generate only 10 values with evenly spaced.

In [125]:
linspace_array = np.linspace(1,20, num=10)
print("linspace array:\n",linspace_array)

print("\nlength of the linspace array: ",len(linspace_array)) 

linspace array:
 [ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]

length of the linspace array:  10


**if we make the `dtype=int` in the above code**

In [126]:
linspace_array = np.linspace(1,20, num=10, dtype=int)
print("linspace array:\n",linspace_array)

print("\nlength of the linspace array: ",len(linspace_array)) 

linspace array:
 [ 1  3  5  7  9 11 13 15 17 20]

length of the linspace array:  10


**if we give the `axis=1` in the above code**

In [131]:
linspace_array = np.linspace(1,20, num=10, dtype=int , axis=-1)
print("linspace array:\n",linspace_array)

print("\nlength of the linspace array: ",len(linspace_array)) 

linspace array:
 [ 1  3  5  7  9 11 13 15 17 20]

length of the linspace array:  10


***

## indices() array
```ruby
numpy.indices(dimensions, dtype=<class 'int'>, sparse=False)
```
Return an array representing the indices of a grid.

Compute an array where the subarrays contain index values 0, 1, … varying only along the corresponding axis.

You can see this for furthur reading.
<a href="https://numpy.org/doc/stable/reference/generated/numpy.indices.html?highlight=numpy%20indices#numpy.indices" > numpy.indices()</a>

In [137]:
np.indices((4,4))

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [138]:
np.indices((4,5))

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

**if `sparse=True`**

In [139]:
np.indices((4,5), sparse=True)

(array([[0],
        [1],
        [2],
        [3]]),
 array([[0, 1, 2, 3, 4]]))

***

## ogrid() array
```ruby
numpy.ogrid = <numpy.lib.index_tricks.OGridClass object>
```
nd_grid instance which returns an open multi-dimensional “meshgrid”.

An instance of numpy.lib.index_tricks.nd_grid which returns an open (i.e. not fleshed out) mesh-grid when indexed, so that only one dimension of each returned array is greater than 1. The dimension and number of the output arrays are equal to the number of indexing dimensions. If the step length is not a complex number, then the stop is not inclusive.

However, if the step length is a complex number (e.g. 5j), then the integer part of its magnitude is interpreted as specifying the number of points to create between the start and stop values, where the stop value is inclusive.

You can see this for furthur reading.
<a href="https://numpy.org/doc/stable/reference/generated/numpy.ogrid.html?highlight=numpy%20ogrid#numpy.ogrid" > numpy.ogrid()</a>

In [142]:
np.ogrid[0:10,0:15]

[array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])]

In [150]:
np.ogrid[-1:10:20j]

array([-1.        , -0.42105263,  0.15789474,  0.73684211,  1.31578947,
        1.89473684,  2.47368421,  3.05263158,  3.63157895,  4.21052632,
        4.78947368,  5.36842105,  5.94736842,  6.52631579,  7.10526316,
        7.68421053,  8.26315789,  8.84210526,  9.42105263, 10.        ])

***

## mgrid() array
```ruby
numpy.mgrid = <numpy.lib.index_tricks.MGridClass object>
```
nd_grid instance which returns a dense multi-dimensional “meshgrid”.

An instance of numpy.lib.index_tricks.nd_grid which returns an dense (or fleshed out) mesh-grid when indexed, so that each returned argument has the same shape. The dimensions and number of the output arrays are equal to the number of indexing dimensions. If the step length is not a complex number, then the stop is not inclusive.

However, if the step length is a complex number (e.g. 5j), then the integer part of its magnitude is interpreted as specifying the number of points to create between the start and stop values, where the stop value is inclusive.

You can see this for furthur reading.
<a href="https://numpy.org/doc/stable/reference/generated/numpy.mgrid.html#numpy.mgrid" > numpy.mgrid()</a>

In [143]:
np.mgrid[0:10,0:15]

array([[[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 0,  1,  

In [148]:
np.mgrid[-1:10:10j]

array([-1.        ,  0.22222222,  1.44444444,  2.66666667,  3.88888889,
        5.11111111,  6.33333333,  7.55555556,  8.77777778, 10.        ])

***
---

## ndarray() 

Now we will see the another method to create the n-dimensional array which is `numpy.ndarray()`.

```ruby
class numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
```
An array object represents a multidimensional, homogeneous array of fixed-size items. An associated data-type object describes the format of each element in the array (its byte-order, how many bytes it occupies in memory, whether it is an integer, a floating point number, or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer to the See Also section below). The parameters given here refer to a low-level method (ndarray(…)) for instantiating an array.

For more information, refer to the `numpy` module and examine the methods and attributes of an array.


You can see this for furthur reading.
<a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html?" > numpy.ndarray()</a>

**ndarray** has some other argument compare to the above function such as *array, zeros, and empty*.

```ruby
buffer: # Used to fill the array with data.
offset: # Offset of array data in buffer.
strides: # Strides of data in memory. 
```

#### making the simple ndarry

In [2]:
# In the making of the simple array we need at least one or two arguments.
# one is the shape of the array and other is the dtype of the array if you want to specify.

# now we will make an array shape of (4,3,2).
np.ndarray([4,3,2] , dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

As we can see that, by default in a simple ndarray creats an array of zeros, Now if we want to make an array with some predefined array like object then we can use the buffer parameter.

#### ndarray with the `buffer` argument.

There are two modes of creating an array using __new__:

1. If buffer is None, then only shape, dtype, and order are used.

2. If buffer is an object exposing the buffer interface, then all keywords are interpreted.

No __init__ method is needed because the array is fully initialized after the __new__ method.

**Examples**
***
These examples illustrate the low-level ndarray constructor. Refer to the See Also section above for easier ways of constructing an ndarray.

First mode, buffer is None:

In [13]:
# this time we will store the array into in a object

# buffer: buffer is used to pass the values or some other array like object which will be used to create the new ndarray

# creating an 1d array with the help of the buffer.
nd_array_1d = np.ndarray([10,], dtype=int, buffer=np.arange(1,20))
print("\none-dimensional array: \n", nd_array_1d)

# creating an 2d array with the help of the buffer.
nd_array_2d = np.ndarray([4,3], dtype=int, buffer=np.arange(1,20))
print("\ntwo-dimensional array: \n", nd_array_2d)


# creating an 3d array with the help of the buffer.
nd_array_3d = np.ndarray([4,3,2], dtype=int, buffer=np.arange(1,25))
print("\nthree-dimensional array: \n", nd_array_3d)


one-dimensional array: 
 [ 1  2  3  4  5  6  7  8  9 10]

two-dimensional array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

three-dimensional array: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


`Note:` if we passing the an array or array like object in the buffer then the length of the array should be equel to the size of the array or gretar then the size of the array.

**TypeError:** buffer is too small for requested array

This TypeError will come when over buffer length is small than the array size as showing in the below cell.

In [14]:
np.ndarray([4,3,2], dtype=int, buffer=np.arange(1,15))

TypeError: buffer is too small for requested array

if we want to check the length of the both buffer array and ndarry then we have to use size property on both of them.

In [16]:
print("Size of the ndarray:",np.ndarray([4,3,2]).size )
print("Size of the buffer array:",np.arange(1,15).size)

Size of the ndarray: 24
Size of the buffer array: 14


As you can see that the size of ndarray and buffer array are not same that's why it show `TypeError`.

**Solution:** we need to pass an array in buffer which has the same or large size to the ndarray. Like in above code if we make the buffer array as
```ruby
np.arange(1,25).size  or  np.arange(1,30).size

```
then in both situation we can create the desired ndarray.

In [17]:
print("Size of the ndarray:",np.ndarray([4,3,2]).size )
print("Size of the buffer array:",np.arange(1,25).size)

Size of the ndarray: 24
Size of the buffer array: 24


In [18]:
array = np.ndarray([4,3,2], dtype=int, buffer=np.arange(1,25))
print(array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


Now we are done with the buffer argument. Now we will see offset argument with buffer.

#### 3. ndarray with `buffer & offset` arguments.

In [41]:
# offset works with the buffer lets see that how offset effets the buffer and the ndarray.

# 1. first of all we will make a 2d aray without offet.
array = np.ndarray([4,3], dtype=int, buffer=np.arange(1,13))
print("ndarry without the offset in buffer:\n",array)

# 2. array with an offset in the buffer
# note that when we use the offset then we need to give the extra number of vaues to the buffer.
# since we in the above array we have passed 13 item but in then we need to give  some extra values according to the offset.

# if offset is 2*itemsize then pass we need ot pass 2 extra item in the buffer
itemsize = np.int_().itemsize
n = 2 # here n can be 1,2,,3,4,5,6,7,8....upto size of the array.

array = np.ndarray([4,3], dtype=int, buffer=np.arange(1,20), offset=n*itemsize)
print("\narry with the offset in buffer:\n",array)

ndarry without the offset in buffer:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

arry with the offset in buffer:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Here in above result there is some difference in the result. the difference is that in second array with offset is do not have the first two element of the `np.arange(1,20)` array.

Because by using the  `offset` we have skipped two  items form the `np.arange(1,20)` array.

#### 4. Exoloring the `buffer` with `offset`.

To explore the offset with buffer we need to answer some the questions.

*  How offset works.
* Why we used the itemsize in the offset
* How offset skips the values.
* How to use the offset.

***1. How offset works***

offset takes the integer value as input but the problem is that it does not takes any integer value. we have to give it according to the our ndarray `dtype.itemsize`. It means we need to calculate the memory size of the one single vlaue which is placed in the array.

In [50]:
# calculating the intemsize of the items in the array.
array = np.ndarray([4,3], dtype=int, buffer=np.arange(1,20), offset=1*np.int_().itemsize)

# we can use also np.int32().intemsize both will give the same result.

print("array: \n",array)
print("\nData type of the array: ",array.dtype)
print("\nMemory size of the single item:",array.itemsize)

array: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

Data type of the array:  int32

Memory size of the single item: 4


Now if we replace our code
```ruby
array = np.ndarray([4,3], dtype=int, buffer=np.arange(1,20), offset=1*np.int_().itemsize)
```
as
```ruby
n=1 # factor of the itemsize
itemsize = np.int32().itemsize
array = np.ndarray([4,3], dtype=int, buffer=np.arange(1,20), offset=n*itemsize)
```
Then `n` will be the factor of the itemsize of the array. now we can simple skip the items by changing the n since we have computed the itemsize.

Now this time we will use the float as the dtype of the array.

In [62]:
# This time array has float type of data, So we need to change the dtype also to compute the itemsize

array = np.ndarray([4,3], dtype=np.float_, buffer=np.arange(1,50))
print("original array:\n",array)

n=3 # factor of the itemsize
itemsize = np.float_().itemsize
array = np.ndarray([4,3], dtype=np.float_, buffer=np.arange(1,50), offset=n*itemsize)


print(f"\narray: skipping first {n} items:\n",array)
print("\nData type of the array: ",array.dtype)
print("\nMemory size of the single item:",array.itemsize)

original array:
 [[4.24399158e-314 8.48798317e-314 1.27319747e-313]
 [1.69759663e-313 2.12199579e-313 2.54639495e-313]
 [2.97079411e-313 3.39519327e-313 3.81959242e-313]
 [4.24399158e-313 4.66839074e-313 5.09278990e-313]]

array: skipping first 3 items:
 [[1.69759663e-313 2.12199579e-313 2.54639495e-313]
 [2.97079411e-313 3.39519327e-313 3.81959242e-313]
 [4.24399158e-313 4.66839074e-313 5.09278990e-313]
 [5.51718906e-313 5.94158822e-313 6.36598737e-313]]

Data type of the array:  float64

Memory size of the single item: 8


***2. why we use the itemsize***

`Ans:` We use the itemsize becaues offset basically takes the memory size of an item. Suppose we have an array with *int* dtype then we need ot pass the offest as 4,8,12,16......and so on, because we need to tell the offeset that this much amout of the data need to be skipped.

***3. How offset skips the values***

`Ans:` indxing or number of element does not work in the offset directly. if we want to make it as the numbers of elements need to be skipped, then we need to compute the itemsize of the array then we can make it as `n*itemsize`. Where *itemsize* is the factor of the real number and the value of the itemsize depends on the array dtype.

***4. How to use the offset.***

`Ans:` To use the offset we need to give some values.
* We need pass the memory size of the item, suppose that if we want to skip first ***n*** number of item then we need to pass `n*(memory size of one item)`. 
* We need to know that what type of data is using in the ndarray to use the offset.

#### 5. ndarray with `strides`.

`ndarray.strides:`
Tuple of bytes to step in each dimension when traversing an array.

The byte offset of element (i[0], i[1], ..., i[n]) in an array a is:
```ruby
offset = sum(np.array(i) * a.strides)
```
A more detailed explanation of strides can be found in the “ndarray.rst” file in the NumPy reference guide.

In [77]:
# This time array has float type of data, So we need to change the dtype also to compute the itemsize

array = np.ndarray([4,5], dtype=int, buffer=np.arange(1,50))
print("original array:\n",array)


array = np.ndarray([4,5], dtype=int, buffer=np.arange(1,50) , strides= [8,8])


print(f"\narray:\n",array)
print("\nData type of the array: ",array.dtype)
print("\nMemory size of the single item:",array.itemsize)

original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

array:
 [[ 1  3  5  7  9]
 [ 3  5  7  9 11]
 [ 5  7  9 11 13]
 [ 7  9 11 13 15]]

Data type of the array:  int32

Memory size of the single item: 4


From the above result we can see that strides are noting but the another method of applying offset to the buffer. offset works in only one-dimensional but the strides can make the offset in n-dimensions.

Suppose that we have a 3d-array then the shape of the 3d-array will be [rows, columns, planes].

Then strides can be applied in the 3d-array in this way.
```ruby
np.ndarray([4,5,2], dtype=int, buffer=np.arange(1,50) , strides= [4,8,4])
```
Here in above code we have passed three values they are for rows, columns, and planes respectively. it means that we are passing an offest for each dimension.

Now if we comput the itemsize and `r=rows, c=columns, p=plane` then the above code can be written as.

```ruby
r = 1 , c=2, p=1
itmesize = np.int_().intemsize
np.ndarray([4,5,2], dtype=int, buffer=np.arange(1,50) , strides= [4,8,4])
```


In [84]:
# original array without strides
array = np.ndarray([4,2,5], dtype=int, buffer=np.arange(1,50))
print("Array without the strides:\n",array)


# Array which is using the strides arguments

r = 1 # this will make the offset in rows  
c = 2 # this will make the offset in columns
p = 1 # this will make the offset in planes


itmesize = np.int_().itemsize
# itemsize is needed to compute that how much amount of data is going to be skipped in each row, column and plane. 

array = np.ndarray([4,2,5], dtype=int, buffer=np.arange(1,50) , strides= [r*itemsize,c*itemsize,p*itemsize])

print("\n\nArray after strides in all dimensions:\n",array)

Array without the strides:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]]]


Array after strides in all dimensions:
 [[[ 1  3  5  7  9]
  [ 5  7  9 11 13]]

 [[ 3  5  7  9 11]
  [ 7  9 11 13 15]]

 [[ 5  7  9 11 13]
  [ 9 11 13 15 17]]

 [[ 7  9 11 13 15]
  [11 13 15 17 19]]]


`Note:` Now from all of the above work we can say that strides is the advance offset in which we can make the offset in each dimension by placing the offset at the place of each dimension.

***For example:***
* `r*itemsize:`  this makes the offset in rows
* `c*itemsize:` this makes the offset in columns
* `p*itemsize:` this makes the offset in planes

These all 

***
---