## First of all import the numpy module

In [1]:
import numpy as np

# numpy.random() Module

In this section we will work on the numpy.random module and its implimantation in the data science

Most common funcion of the random modules are.

* numpy.random.random()
* numpy.random.rand()
* numpy.random.randn()
* numpy.random.randint()
* numpy.random.random_sample()
* numpy.random.random_integers()
* numpy.random.choice()

### 1. numpy.random.random()
```ruby
random(size=None)
```
Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.


* First of all we will see that how random works. Since random only takes one argument and that argument is the size of the array.


In [5]:
# 1. random function of the random class in numpy.

np.random.random((4,2))

array([[0.72952913, 0.42908422],
       [0.47079735, 0.243812  ],
       [0.393077  , 0.99590081],
       [0.32099304, 0.97212375]])

Random function of the random class does not have any other argument so we are done with the `np.random.random()` function.
***

## 2. numpy.random.rand()
```ruby
rand(d0, d1, ..., dn)
```
Random values in a given shape.

This function takes the n parameters as shape of the output or desired result in which all the argument are the shape values. The output will be according to the given shape.

**creating an array having a shape of (3,2,1)**

In [7]:
# 2. rand function in the random class.

np.random.rand(3,2,1)

array([[[0.55684481],
        [0.49152949]],

       [[0.63178713],
        [0.16742483]],

       [[0.03846722],
        [0.68848692]]])

**creating an array having a shape of (5,4,3,2)** 

In [11]:
# shape = (5,4,3,2)

rand_array = np.random.rand(5,4,3,2)
print(rand_array)

[[[[0.63890261 0.07504637]
   [0.66434503 0.05465705]
   [0.38981777 0.54450993]]

  [[0.94618289 0.97252164]
   [0.93946935 0.90217431]
   [0.76110369 0.24627802]]

  [[0.85494758 0.76054344]
   [0.05901945 0.3087478 ]
   [0.9367858  0.02845257]]

  [[0.35563543 0.88613542]
   [0.46544782 0.96180228]
   [0.51596369 0.18883559]]]


 [[[0.93917668 0.3252935 ]
   [0.67805158 0.51468751]
   [0.02201133 0.88526434]]

  [[0.63140171 0.82079545]
   [0.03346929 0.51380735]
   [0.42626078 0.66365645]]

  [[0.75064095 0.33721963]
   [0.75514139 0.47260839]
   [0.98114615 0.33688789]]

  [[0.20953854 0.62241718]
   [0.13714061 0.63788332]
   [0.56770895 0.07137547]]]


 [[[0.05329385 0.81839523]
   [0.15171122 0.77114964]
   [0.63359429 0.590501  ]]

  [[0.51534257 0.89221415]
   [0.34459237 0.56245487]
   [0.88104408 0.97649887]]

  [[0.37489805 0.2032884 ]
   [0.81492133 0.5542299 ]
   [0.86175628 0.61191274]]

  [[0.93076259 0.32200435]
   [0.86417596 0.73668626]
   [0.59513072 0.9522764 ]]]


As you can see that our result is very long and very large, so we can see that our `np.random.rand()` function does not takes  any other parameters other than shape of the desired array. 

if you want to check the shape and dimension of the array then we can do it with the help of the ndarray property attributes.

In [12]:
# to check the shape we use ndarray.shape
print("Shape of the above rand array: ",rand_array.shape)

# to check the dimension we need to use ndarray.ndim
print("Dimension of the above rand array: ",rand_array.ndim)

Shape of the above rand array:  (5, 4, 3, 2)
Dimension of the above rand array:  4


As we given we have got our result now we should move on to the `randn` function. 

## 3. numpy.random.randn()
```ruby
numpy.random.randn(d0, d1, ..., dn)
```
Return a sample (or samples) from the "standard normal" distribution.

This function generates N-dimensional array which contains both negative and positive values. This method use the gaussion distribution method to generate the uniform random numbers.

In [14]:
np.random.randn(4,3,2)

array([[[ 0.68007514, -0.08385047],
        [ 1.57425745,  1.06391927],
        [-0.57639136, -0.8983189 ]],

       [[-2.16935359,  2.4493302 ],
        [ 1.62496659, -0.46989534],
        [ 0.63610703, -0.64561476]],

       [[ 0.93314148,  0.37388158],
        [ 0.44468941,  0.36993568],
        [ 0.10303313, -0.80758421]],

       [[-2.20014653, -0.64536125],
        [-0.69997252, -1.66649297],
        [-1.31251828,  0.48167002]]])

***

## numpy.random.randint()
```ruby
randint(low, high=None, size=None, dtype=int)
```
Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [`low`, `high`). If `high` is None (the default), then results are from [0, `low`).

This function contains 4 arguments in which:

`low:` low is the lower range in which the random numbers are going to generate.(*inclusive*)

`high:` High is the upper range in which the random numbers are going to be generates.(*exclusive*)

`size:` size is shape of the desired array.

`dtype:` dtype is the data type of the array items.

In [21]:
# making the random numbers in b/w (1,100)
# dtype = int
randint_array = np.random.randint(1,100, (3,5))
print(randint_array)

[[42  2 51 11 17]
 [90 16 91 51 21]
 [33 27 93 41  5]]


We can see that we have created an array which  is having iterm in b/w a particular range defined by the low and high parameters. The dtype of the array is int by default but we will ensure that it is really int on something else.

Now we will check some peoperties like shape, size, itemisze, dtype etc.

In [20]:
# checking the shape of the array
print("Shape of the array:", randint_array.shape)

# checking the size of the array
print("Size of the array:",randint_array.size)

# checking the itemsize of the array
print("Itemsize of the array:",randint_array.itemsize)

# checking the dtype of the array.
print("Dtype of the array:",randint_array.dtype)

Shape of the array: (3, 5)
Size of the array: 15
Itemsize of the array: 4
Dtype of the array: int32


As you can see that we have created an array and checked it again, and found that array is created as we thought and we have confirmed by using the some of the array properties like shape, size , itemsize and dtype of the array.

***

## numpy.random.sampel()

This is an alias of `random_sample`.

In [22]:
#np.random.sample()

## numpy.random.random_sample()
```ruby
random_sample(size=None)
```
Return random floats in the half-open interval [0.0, 1.0).

Results are from the "continuous uniform" distribution over the
stated interval.  To sample :math:`Unif[a, b), b > a` multiply
the output of `random_sample` by `(b-a)` and add `a`::

 ` (b - a) * random_sample() + a`
 
 Here:
 
 `a:` it is the *lower* value which is *inclusive* in the range of random generator
 
 `b:` It is the *upper* value which is *exclusive* in the range of the random generator.
 
 This random_sample function also takes an argument which is the size (shape) of the array (output array).
 
 **1. random_sample without any size**

In [23]:
# since we are generating an array without passing any size then.

rsample = np.random.random_sample()
print(rsample) # this will generate a float dtype array.

0.06040143374463225


As we can see that it when we do not pass any size then this generates a single random value which is float in dtype, this function do not give us any argument or functionality to change the dtype of generating values it will be always float in dtype.

**2. random_sample with a size**

In [24]:
# This time we will pass an shape of the array.

rsample = np.random.random_sample(size=(3,4))
print(rsample)

[[0.70946128 0.15879374 0.27626707 0.33284567]
 [0.25413469 0.39854497 0.02079602 0.85118969]
 [0.01793492 0.05300143 0.30826969 0.88573902]]


Now we can see that this generates an array with a given shape and the dtype of the items are also float in nature. but this array is random there is no range of the output values.

What if we want to generates some random values in a particular range, then we will follow the method `(b-a)*random_sample()+a` to generate the random numbers in the range[a,b). in which a is inclusive and the b is exclusive.

**3. random_sample in a given range**

In [31]:
# Now we wil generates some numuber in the given range.

rsample = np.random.random_sample(size=(3,4)) # we are using the same size as the previous one so we con compare the result.
print("random sample without range :\n",rsample)

b,a = 5,-5  # this will generates the numbers in b/w [-5,10) 
rsample = (b-a)* np.random.random_sample(size=(3,4)) + a
print("\n\nrandom sample with a range:\n",rsample)


random sample without range :
 [[0.21133031 0.21247784 0.17399014 0.7028964 ]
 [0.84585352 0.06970864 0.52219589 0.59743636]
 [0.18351814 0.14212707 0.927996   0.44974801]]


random sample with a range:
 [[-3.72929418  1.24295917  1.8040077   4.37740952]
 [-2.19979613 -2.04008613 -3.90458452  2.72976718]
 [ 2.76194438  2.31641551 -1.16567728 -0.31111729]]


In [34]:
# another example with an vector 
b,a = 5,-5
rsample = (b-a) * np.random.random_sample(size=(10,)) + a
# this will generates the 1d array or a vector in a range of [-5,5) 

print(rsample)

[ 1.54611098  2.11429992 -4.93073963 -0.70835665  4.18323288 -1.36067667
 -4.60723531  2.15059125  0.93310887 -1.47010793]


To understand the range concept we wil make another array in another range.

Target range:------> [5,0)

it means that our a = 5 and b = 0

now according to the the formula to create the range function is that we need to multiply `(b-a)` with  `rndom_sample()` and need to add `a`. by doing  this it will generate the random number in the Target range.

**Example 1**

In [63]:
# Taget range:----------> [0,5)  where b > a

b,a = 5 , 0 
line = 100
# a and b are taken from the range.
print(f"Lower range a: {a}")
print(f"Upper range b: {b}\n")

# Geenrating a 1d random array in the given range.

rsample = (b-a) * np.random.random_sample(size=(10,)) + a

print(f"\n {(b-a)} * {'np.random.random_sample(size=(10,))'} + ({a})")

# the above line can be written as the 5 * np.random.random_sample(size=(10,)) + 0
print(f"{'_'*line}")
print("\nrandom_sample in the half-open interval [0,5)\n\n", rsample)
print(f"{'_'*line}")

Lower range a: 0
Upper range b: 5


 5 * np.random.random_sample(size=(10,)) + (0)
____________________________________________________________________________________________________

random_sample in the half-open interval [0,5)

 [1.46044041 4.86694928 0.95407778 0.39286663 3.98789528 0.08531375
 3.82579891 4.46372758 0.21860775 1.16465465]
____________________________________________________________________________________________________


**Example 2**

In [62]:
# Taget range:----------> [-5,0) where b > a
line = 100

b, a  = 0, -5 # a and b are taken from the range.
# a and b are taken from the range.
print(f"Lower range a: {a}")
print(f"Upper range b: {b}\n")

# Geenrating a 1d random array in the given range.

rsample = (b-a) * np.random.random_sample(size=(10,)) + a
print(f"\n {(b-a)} * {'np.random.random_sample(size=(10,))'} + ({a})")
# the above line can be written as the 5 * np.random.random_sample(size=(10,)) - 5
print(f"{'_'*line}")
print("\nrandom_sample in the half-open interval [-5,0)\n\n", rsample)
print(f"{'_'*line}")

Lower range a: -5
Upper range b: 0


 5 * np.random.random_sample(size=(10,)) + (-5)
____________________________________________________________________________________________________

random_sample in the half-open interval [-5,0)

 [-2.10616978 -0.60560178 -2.86851344 -1.98063182 -3.04817592 -3.48397826
 -2.76213706 -2.17490407 -4.31277699 -3.21696853]
____________________________________________________________________________________________________


As we can see in the both Example 1 and the Example 2, we have got our desired result in the desired range as we thaught but still we need to understand that how it works, for that we need to break the code into three parts.

* random_sample()
* multiply (b-a) 
* add a

**Breaking the above result code**

first of all we need to see about the random_sample.

In [65]:
# creating the random sample to analysis it
np.random.random_sample(size=(10,))

array([0.32499663, 0.85421945, 0.50933069, 0.12742628, 0.97398831,
       0.34586032, 0.51319776, 0.67346228, 0.57546226, 0.42283627])

Now we can see that all the values are b/w the (0.0,1.0), From the documentation we have found that it generates the values in half-open interval in `[0.0, 1.0) ` 

So if we muliply it  from some value (X) then all the values multiplied from that valuea and we can generate values from 0 to X. 

In [69]:
# multiplying the random_sample form the X value
X = 5

rsample = X * np.random.random_sample(size=(10,))
print(rsample)

[0.72985836 0.05728082 2.16953448 4.11911885 1.16731283 0.25994343
 2.66289224 2.53783647 3.54802013 3.91487207]


As we can see that we have created values form the [0,5) but in this 5 is not incluive becaues 1 was not inclusive during the generation of the random values. so we can create the random values in b/w [0.0, 5.0) half open interval.

Now if we add some other value say Y in the `rsample` result then it will generate the number in b/w `[X,Y)` range in which X would be inclusive. 

`Note:` In this whole process Y > X

In [70]:
# since X > Y then Y should be small then the X so we take the Y as the -5

Y = -5

# adding the in the rsample
rsample + Y

array([-4.27014164, -4.94271918, -2.83046552, -0.88088115, -3.83268717,
       -4.74005657, -2.33710776, -2.46216353, -1.45197987, -1.08512793])

Now you can see that all the values are negative or we can say that all values are in b/w [0.0 ,  -5) . 

but if we take non negative value of Y then.

In [71]:
# taking the Y as positive and small to X

Y = 2  # Y < X

rsample + Y

array([2.72985836, 2.05728082, 4.16953448, 6.11911885, 3.16731283,
       2.25994343, 4.66289224, 4.53783647, 5.54802013, 5.91487207])

Now you can see that the range is changed from `[0.0 , 5.0)` ---------------------> `[2,0, 7.0)`

but the problem we didn't used the value 7.0 to get this range so what happend. Well this is just simple Mathematics. Let's break all the operations.

**Point 1**

In [72]:
np.random.random_sample(size=(10,))

array([0.16039843, 0.8577194 , 0.48684179, 0.59724195, 0.29276744,
       0.47218278, 0.70777807, 0.74815284, 0.98184573, 0.3069532 ])

_np.random.random_smple()_  generates some random values from 0 to 1 in float in which 1 is not inclusive so all the values are in b/w 0 to 1 but there will no 1 incuded.

**Point 2**

So if we muliply some X value then this X will be multiplied to all the values if we use the for loop to visulize the all computation then we can see that what is going on.

In [85]:
# Since we need to match the result so we will take the X as 5
X = 5

# but we need to create a fresh  a new rsample 

rsample = np.random.random_sample(size=(10,))

print("Our oringianl values are: \n\n", rsample)
# iterating over the all values 

print("\nOur new values after the multiplying the X values in the rsample\n")
for values in rsample:
    
    # using the rsample which is saved in the memories already and by this our result will match.

    # we will print all the vlaues to understand the computation
    
    print(f"{X} * {values} = {X*values}")

Our oringianl values are: 

 [0.99460423 0.10049994 0.1753754  0.34073775 0.72674755 0.09511575
 0.20043972 0.40826225 0.01564071 0.03258093]

Our new values after the multiplying the X values in the rsample

5 * 0.9946042292772675 = 4.973021146386338
5 * 0.100499937750122 = 0.50249968875061
5 * 0.1753754044201714 = 0.876877022100857
5 * 0.34073775476562507 = 1.7036887738281252
5 * 0.7267475490417133 = 3.633737745208567
5 * 0.09511575267932626 = 0.4755787633966313
5 * 0.20043971761490875 = 1.0021985880745437
5 * 0.40826224627998364 = 2.041311231399918
5 * 0.01564070869399925 = 0.07820354346999625
5 * 0.03258092719347494 = 0.1629046359673747


Now we use our direct mehod to multiply the vlaues to crate the array. 

In [86]:
X * rsample

array([4.97302115, 0.50249969, 0.87687702, 1.70368877, 3.63373775,
       0.47557876, 1.00219859, 2.04131123, 0.07820354, 0.16290464])

As you can see that all values are same to the above result by doing this we have created the range from 0 ot 5,

but now we will add the Y, but the Y is small to the X

In [87]:
Y =2
X * rsample + 2

array([6.97302115, 2.50249969, 2.87687702, 3.70368877, 5.63373775,
       2.47557876, 3.00219859, 4.04131123, 2.07820354, 2.16290464])

Now we will see the all values in the for loop

In [90]:
Y = 2
X_rsample = X*rsample

for values in X_rsample:
    
    print(f" {values} + {Y}  =  {values+Y}")

 4.973021146386338 + 2  =  6.973021146386338
 0.50249968875061 + 2  =  2.50249968875061
 0.876877022100857 + 2  =  2.876877022100857
 1.7036887738281252 + 2  =  3.7036887738281252
 3.633737745208567 + 2  =  5.633737745208567
 0.4755787633966313 + 2  =  2.4755787633966313
 1.0021985880745437 + 2  =  3.0021985880745437
 2.041311231399918 + 2  =  4.041311231399918
 0.07820354346999625 + 2  =  2.0782035434699964
 0.1629046359673747 + 2  =  2.162904635967375


Now we can see that we have got our new vlaues in the b/w the 2 to 7. From all of this we can say that range can be manuplate by using the X and Y but still we need to be clear that how we decide the range. use the all computation b/w the X and Y.

X = 5 ||
Y = 2

all possible computation are add, multiply, deivde, subtract.

`X + Y = 7 `       |       `X -Y = 3`         |            `X /Y = 2.5`           |           `X*Y = 10`

from this we have found the relation to get the final range of the values.

So we found two result as the range is that .

Y = 2 and X+Y = 7

Now if we take the `Y = a` as the lower range  and `X+Y = b` as the upper range in which *y > a*.

So from all this computation we have got the lower value and the upper value of the range.
Now the equation `X+Y=b` becomes `X+a = b`  and then X becomes  `X = b-a`.

In [93]:
# Now if we compute the above valus

X = 5
Y = 2

print(f" range :[{Y},{X+Y})")

 range :[2,7)


from the above result we have got the if we want to generate an array in b/w [a,b) range then as showing in the above reslut [2,7) we need to give the input as 

`lower range  = 2`  and `upper range = X + lower range`

but in the Above example we have used X and Y as to generate the random values `X*random_sample(size)+Y` but in after Computation this gives us the different range output from the input range as X and Y, but also we have found that our lower range is `lower range = a = Y`  and then the X becomes `             X = upper range - lower range` and we know that our lower range is `a` and the upper range `b`.

So X and Y becomes: 

`X = b-a`  

`Y = a`

So our equation of  `rsample = X * random_sample(size) + Y` becomes  ` rsample = (b-a) * random_sample(size) + a`. Where `a` is the lower value of the range and the `b` is the upper value of the range array.

Now we have understand the concept of the random_sample() now we will generate the values in b/w the [10 . 20)

In [97]:
# creating the values in b/w the the range [10 . 20) where b > a

# from the range we have
a = 10  # lower value
b = 20  # upper value

# so our final sample is

(b-a) * np.random.random_sample(size=(10,)) + a

array([16.8765738 , 14.22567961, 16.23765942, 15.52789411, 13.27575265,
       18.86995207, 19.56821628, 10.39116099, 14.54947583, 11.71462581])

From the abo