In [4]:
import numpy as np
from numpy import arange , ndarray
from numpy.random import randint

# Indexing

Indexing is a method to access an item of an object by using their contigous loaction like array.  Since we are working on the array and numpy arrays are N-dimensioal so there are some complexity comes when we try to access an item by using indexing in a N-dimensional array. Now we will try to understand them by starting from a single item accessing in 1D array.

In this section for now we will only see upto 3-dimesional array.

### 1. Access an item from a single array:

first of all we need an array so we will create an array with arange function.

In [3]:
array =  arange(10)

# Now we have an array let's print it 
print("Array: ", array)

Array:  [0 1 2 3 4 5 6 7 8 9]


Now if we want to access any item from like 7 then we need to start from 0 because indexing always starts from 0, so if we want to access it then we need to count from 0 to up to the element position in this case element 7 is at the index number 7th.

In [5]:
# To access an element we need to use the square bracket [] after the array object like 
# array[index]

array[7]

7

As you can see that we have got 7 now we will use an random number array to see the it againl.

In [9]:
# creating an random array with randint

array = randint(1,50,size=(20,))
print("array: ", array)

array:  [13 25 33 36 36  2  1 41 31  7 47 36 48 28 45 46  7 46 29  9]


As you can see that we have a new random array in which all are int type not lets say we want to access 10th element of the array. then we need to pass `(n-1)` for the indexing. We can see that the 10th element is 7 and by using indexing we will access it.

In [10]:
# accessing the 10th element
array[9] # (n-1) indexing number 

7

In [11]:
# accessing teh 15th element
array[14]

45

**Reversive indexing**

We can access the 14th element from the right side of the array by using the negative indexing [-n]. Like , if we want to access the 15th element of the array then we count it from the right side and put a negative sign on the number at which the element is present. Like 45 is present at the 6th location from right side of the array then we need to use indexing like this `array[-6]`.

In [12]:
# accessing the 15th element form the right side (negagtive indexing.)
array[-6]

45

## Single element idexing with 2-d array

Since Numpy contains N-dimensional array like this 2-d array also comes in the N-dimensional but in 2d array we have only two sub array in a single thats why its dimension is 2d. Now when we create an 2d array then there are two thing comes in picture these are Row and Column of the array which can be seen like this `array[Row ,  Column]`.

Let's see how it looks like:

In [14]:
# creating a 2d array
array = randint(1,20,size=(5,4))
print("2D array:\n", array)
print("\nShape of the array:",array.shape)
print("Dimension of the array: ",array.ndim)

2D array:
 [[ 1 10 17 16]
 [ 9 11 10  8]
 [ 1 14 19 19]
 [17  7 16  8]
 [ 4 15  1 18]]

Shape of the array: (5, 4)
Dimension of the array:  2


As you can see that we have got an  2d array and also we have checked its shape and the dimension with `shape` and `ndim` property of the array. Now since it is a two dimension then we need also two index number one is for the `rows` of the array and the other number is for the the `Column` of the array.

In [16]:
# accessing  an item from the 2d array
# So we need Rows number and Column number to access the element of the array 
# sicne from the shape of the array we can see that new array conatains 5 Rows and 4 Columns for we cant got beyond these numbers.

# Lets acces an element which is present in 3rd row and 2nd Conlumn
array[2,1] # 2 is for the row indexing and 1 is for the column indexing 

# Since indexing starts from the 0 number 

14

In [17]:
array

array([[ 1, 10, 17, 16],
       [ 9, 11, 10,  8],
       [ 1, 14, 19, 19],
       [17,  7, 16,  8],
       [ 4, 15,  1, 18]])

As you can see in above array then element 14 is placed at the 3rd row and 2nd column. So we have seen that for accessing an element in a 2d array we need two indexing number first one is for the `Rows` of the array and the other one if for `Columns` of the array.

## Selecting a Row or a Column of an arrray:

After selecting an array we will select an entire Row and an entire Column of the array. Because we have already have an 2D array so we don't need to make another one.

In [18]:
# Printing the over old 2D array 
print(array)

[[ 1 10 17 16]
 [ 9 11 10  8]
 [ 1 14 19 19]
 [17  7 16  8]
 [ 4 15  1 18]]


**Selecting an Row of 2D array**

Selecting a row and Column is very simple we just need to give only one number any of two number `(Rows and Column)`. if we want to select a row then we need to give that rows number. Like we want to select 3rd row then we need to use the `array[2]`. 

In this we are only accessing Row element and do not specifing any colulmns, by doing this it will count all the column and return all the items from all the column.

In [19]:
# Accessing 3rd row of the array
array[2]

array([ 1, 14, 19, 19])

In [20]:
# the above accesing of 3rd row is also written as
array[2,:]

array([ 1, 14, 19, 19])

Here `:` represents slicing of the element which has the real representation as `n1:n2` . but in the above cell we didn't provide any n1 and n2  and the single `:` represents that we need all the element of the current dimension and in this case the current dimension is Column of the array.

**Accessing Column of the array**

Like Accessing the row of the array , selection of column is also similar to the the selection of the row, we just need to left blank the rows indexing and just need to specify the column which we want to access.


In [21]:
# Like we want to access 3rd Column of the array
# we need to left empty of the rows index

array[,2]

SyntaxError: invalid syntax (<ipython-input-21-873bd565f691>, line 4)

OH NOO! We have got an error but we left the rows place empty and provided the columns index number then what is wrong with it. 

The problem is that here empty means we need to specify `:` to the rows. it means that we need all from this dimenion (row). So let's try again with `:` this.

In [22]:
array[:,2]

array([17, 10, 19, 16,  1])

See that we have got the 3rd column of the array. Now we will access a section of an array.

## Select a section of a 2D-array:

Lets say that we have a big 2D array of 36 element which is 6 x 6  and we want to access a particular section of that array then we need to use the slicing of the array which can be done by using `n1:n2` in a that dimension in which we want to slice the array. 

First of all we will make a new big array:

In [25]:
# Making a 6 x 6 array
array = randint(1,100, size = (6,6))
print("Array: \n",array)
print("\nShape of the array:", array.shape)
print("Total elements in the array: ", array.size)

Array: 
 [[85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [55 24 52 38 81 11]
 [ 6 89 92 65 39 19]
 [62 45 57 25 94 88]
 [84 62  9 26 57 47]]

Shape of the array: (6, 6)
Total elements in the array:  36


Now from the above output we can see that we have an 2D array with a shape of (6,6 ) and it has 36 elements. So now we need to select a particular area of the element.
```ruby
 array =      [[24 52 38]
               [89 92 65]
               [45 57 25]]
```

Now we will select the above section of the current array:

In [26]:
# To select this kind of section we need to use the slicing of the array n1:n2
# we need slicing in the both row and column so we need to use like this

# array[n1:n2 , n1:n2]

# first n1:n2 is for the slicing of the the Rows
# Second n1:n2 is for the slicing of the columns

# we can write this as also --------> array[start:end , start:end]
# This clear the confusion that we need a starting point and ending point in both rows and columns

# now count the rows starting point and ending point of the rows and columns
# rows----> 2:4  # these are index nunbers not position number
# column------> 1:3

# Now accessing the section
array[2:4 , 1:3]

array([[24, 52],
       [89, 92]])

Oh no....! the result is not seem to match our task, So what happened.

`Note:` End point in the slicing is not inclusive so we need of proved the `n+1` in the end indexing point. So our New slicing becomes as.

Rows = 2:5 

Columns = 1:4


In [27]:
# accessing again
array[2:5, 1:4]

array([[24, 52, 38],
       [89, 92, 65],
       [45, 57, 25]])

Now we can see that, we have got our desired result but the thing is to be remember is that `end` point in the slicing of the array dimension is not inclusive so we need to provide `(n+1)`  index number to get the desired result.

#### Selection without start or end point:

Selection without start point or end point is used when we need to slice something from begning of the column or the row and slicing something upto end of the rows and the columns.

**Example 1**
```ruby
array([[85, 10, 91],
       [21, 30, 20],
       [55, 24, 52],
       [ 6, 89, 92]])
```

Select this setion from the array:(old array which is used in previous selection)

In [30]:
# printing array again
print(array)

[[85 10 91 31 56 51]
 [21 30 20 94 45 37]
 [55 24 52 38 81 11]
 [ 6 89 92 65 39 19]
 [62 45 57 25 94 88]
 [84 62  9 26 57 47]]


As from the example 1 task we can see that section starts from 0th row and 0th column, in this case we do not need to provide the starting point during the slicing of the array. we can use `array[:end, :end]` like slicing beacause both start point are at 0th indexing.

In [31]:
# accesing the given array on example 1
array[:4,:3] # since we need first four rows 0 to 3 ||| and we need first three column from 0 to 2 
# Since end point of indexing need to provide as (n+1)

array([[85, 10, 91],
       [21, 30, 20],
       [55, 24, 52],
       [ 6, 89, 92]])

As you can see that we have got our result.

**Example 2**

```ruby
array([[39, 19],
       [94, 88],
       [57, 47]])
```

In [38]:
# Count the rows and columns to match the start:points of exampel 2 section

# Rows------------>  3:6  # since we have only 6 rows so we can write this as => 3: this says count all the rows after 3rd row
# Columns--------->  4:6  # can be written as => 4: count all column after 4
array[3:, 4:]

array([[39, 19],
       [94, 88],
       [57, 47]])

**Example 3**

```ruby
array([[21, 30, 20, 94],
       [55, 24, 52, 38],
       [ 6, 89, 92, 65]])
```

In [39]:
# Count the rows and columns to match the start:points of exampel 4 section

# Rows------------>  1:(3+1)  
# Columns--------->  0:(3+1)  can be written as => :4

array[1:4 , :4]

array([[21, 30, 20, 94],
       [55, 24, 52, 38],
       [ 6, 89, 92, 65]])

**Example 4**
```ruby
array([[20, 94, 45, 37],
       [52, 38, 81, 11],
       [92, 65, 39, 19]])
```

In [40]:
# Count the rows and columns to match the start:points of exampel 4 section

# Rows------------>  1:(3+1)  
# Columns--------->  2:6  can be written as => 2:

array[1:4 , 2:]

array([[20, 94, 45, 37],
       [52, 38, 81, 11],
       [92, 65, 39, 19]])

`Conclusion:` From  all of the above example in the slection (slicing) of an array  gives us the overall overview that we can access any section of the array with the help of the slicing in this syntex `array[start:end+1 , start:end+1]`. Since end point is not inclusive in the slicing 