## First of all import the numpy module

In [1]:
import numpy as np

# numpy.random() Module

In this section we will work on the numpy.random module and its implimantation in the data science

Most common funcion of the random modules are.

* numpy.random.random()
* numpy.random.rand()
* numpy.random.randn()
* numpy.random.randint()
* numpy.random.random_sample()
* numpy.random.random_integers()
* numpy.random.choice()

### 1. numpy.random.random()
```ruby
random(size=None)
```
Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.


* First of all we will see that how random works. Since random only takes one argument and that argument is the size of the array.


In [5]:
# 1. random function of the random class in numpy.

np.random.random((4,2))

array([[0.72952913, 0.42908422],
       [0.47079735, 0.243812  ],
       [0.393077  , 0.99590081],
       [0.32099304, 0.97212375]])

Random function of the random class does not have any other argument so we are done with the `np.random.random()` function.
***

## 2. numpy.random.rand()
```ruby
rand(d0, d1, ..., dn)
```
Random values in a given shape.

This function takes the n parameters as shape of the output or desired result in which all the argument are the shape values. The output will be according to the given shape.

**creating an array having a shape of (3,2,1)**

In [7]:
# 2. rand function in the random class.

np.random.rand(3,2,1)

array([[[0.55684481],
        [0.49152949]],

       [[0.63178713],
        [0.16742483]],

       [[0.03846722],
        [0.68848692]]])

**creating an array having a shape of (5,4,3,2)** 

In [11]:
# shape = (5,4,3,2)

rand_array = np.random.rand(5,4,3,2)
print(rand_array)

[[[[0.63890261 0.07504637]
   [0.66434503 0.05465705]
   [0.38981777 0.54450993]]

  [[0.94618289 0.97252164]
   [0.93946935 0.90217431]
   [0.76110369 0.24627802]]

  [[0.85494758 0.76054344]
   [0.05901945 0.3087478 ]
   [0.9367858  0.02845257]]

  [[0.35563543 0.88613542]
   [0.46544782 0.96180228]
   [0.51596369 0.18883559]]]


 [[[0.93917668 0.3252935 ]
   [0.67805158 0.51468751]
   [0.02201133 0.88526434]]

  [[0.63140171 0.82079545]
   [0.03346929 0.51380735]
   [0.42626078 0.66365645]]

  [[0.75064095 0.33721963]
   [0.75514139 0.47260839]
   [0.98114615 0.33688789]]

  [[0.20953854 0.62241718]
   [0.13714061 0.63788332]
   [0.56770895 0.07137547]]]


 [[[0.05329385 0.81839523]
   [0.15171122 0.77114964]
   [0.63359429 0.590501  ]]

  [[0.51534257 0.89221415]
   [0.34459237 0.56245487]
   [0.88104408 0.97649887]]

  [[0.37489805 0.2032884 ]
   [0.81492133 0.5542299 ]
   [0.86175628 0.61191274]]

  [[0.93076259 0.32200435]
   [0.86417596 0.73668626]
   [0.59513072 0.9522764 ]]]


As you can see that our result is very long and very large, so we can see that our `np.random.rand()` function does not takes  any other parameters other than shape of the desired array. 

if you want to check the shape and dimension of the array then we can do it with the help of the ndarray property attributes.

In [12]:
# to check the shape we use ndarray.shape
print("Shape of the above rand array: ",rand_array.shape)

# to check the dimension we need to use ndarray.ndim
print("Dimension of the above rand array: ",rand_array.ndim)

Shape of the above rand array:  (5, 4, 3, 2)
Dimension of the above rand array:  4


As we given we have got our result now we should move on to the `randn` function. 

## 3. numpy.random.randn()
```ruby
numpy.random.randn(d0, d1, ..., dn)
```
Return a sample (or samples) from the "standard normal" distribution.

This function generates N-dimensional array which contains both negative and positive values. This method use the gaussion distribution method to generate the uniform random numbers.

In [14]:
np.random.randn(4,3,2)

array([[[ 0.68007514, -0.08385047],
        [ 1.57425745,  1.06391927],
        [-0.57639136, -0.8983189 ]],

       [[-2.16935359,  2.4493302 ],
        [ 1.62496659, -0.46989534],
        [ 0.63610703, -0.64561476]],

       [[ 0.93314148,  0.37388158],
        [ 0.44468941,  0.36993568],
        [ 0.10303313, -0.80758421]],

       [[-2.20014653, -0.64536125],
        [-0.69997252, -1.66649297],
        [-1.31251828,  0.48167002]]])

***

## numpy.random.randint()
```ruby
randint(low, high=None, size=None, dtype=int)
```
Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [`low`, `high`). If `high` is None (the default), then results are from [0, `low`).

This function contains 4 arguments in which:

`low:` low is the lower range in which the random numbers are going to generate.(*inclusive*)

`high:` High is the upper range in which the random numbers are going to be generates.(*exclusive*)

`size:` size is shape of the desired array.

`dtype:` dtype is the data type of the array items.

In [21]:
# making the random numbers in b/w (1,100)
# dtype = int
randint_array = np.random.randint(1,100, (3,5))
print(randint_array)

[[42  2 51 11 17]
 [90 16 91 51 21]
 [33 27 93 41  5]]


We can see that we have created an array which  is having iterm in b/w a particular range defined by the low and high parameters. The dtype of the array is int by default but we will ensure that it is really int on something else.

Now we will check some peoperties like shape, size, itemisze, dtype etc.

In [20]:
# checking the shape of the array
print("Shape of the array:", randint_array.shape)

# checking the size of the array
print("Size of the array:",randint_array.size)

# checking the itemsize of the array
print("Itemsize of the array:",randint_array.itemsize)

# checking the dtype of the array.
print("Dtype of the array:",randint_array.dtype)

Shape of the array: (3, 5)
Size of the array: 15
Itemsize of the array: 4
Dtype of the array: int32


As you can see that we have created an array and checked it again, and found that array is created as we thought and we have confirmed by using the some of the array properties like shape, size , itemsize and dtype of the array.

***

## numpy.random.sampel()

This is an alias of `random_sample`.

In [22]:
#np.random.sample()

## numpy.random.random_sample()
```ruby
random_sample(size=None)
```
Return random floats in the half-open interval [0.0, 1.0).

Results are from the "continuous uniform" distribution over the
stated interval.  To sample :math:`Unif[a, b), b > a` multiply
the output of `random_sample` by `(b-a)` and add `a`::

 ` (b - a) * random_sample() + a`
 
 Here:
 
 `a:` it is the *lower* value which is *inclusive* in the range of random generator
 
 `b:` It is the *upper* value which is *exclusive* in the range of the random generator.
 
 This random_sample function also takes an argument which is the size (shape) of the array (output array).
 
 **1. random_sample without any size**

In [23]:
# since we are generating an array without passing any size then.

rsample = np.random.random_sample()
print(rsample) # this will generate a float dtype array.

0.06040143374463225


As we can see that it when we do not pass any size then this generates a single random value which is float in dtype, this function do not give us any argument or functionality to change the dtype of generating values it will be always float in dtype.

**2. random_sample with a size**

In [24]:
# This time we will pass an shape of the array.

rsample = np.random.random_sample(size=(3,4))
print(rsample)

[[0.70946128 0.15879374 0.27626707 0.33284567]
 [0.25413469 0.39854497 0.02079602 0.85118969]
 [0.01793492 0.05300143 0.30826969 0.88573902]]


Now we can see that this generates an array with a given shape and the dtype of the items are also float in nature. but this array is random there is no range of the output values.

What if we want to generates some random values in a particular range, then we will follow the method `(b-a)*random_sample()+a` to generate the random numbers in the range[a,b). in which a is inclusive and the b is exclusive.

**3. random_sample in a given range**

In [31]:
# Now we wil generates some numuber in the given range.

rsample = np.random.random_sample(size=(3,4)) # we are using the same size as the previous one so we con compare the result.
print("random sample without range :\n",rsample)

b,a = 5,-5  # this will generates the numbers in b/w [-5,10) 
rsample = (b-a)* np.random.random_sample(size=(3,4)) + a
print("\n\nrandom sample with a range:\n",rsample)


random sample without range :
 [[0.21133031 0.21247784 0.17399014 0.7028964 ]
 [0.84585352 0.06970864 0.52219589 0.59743636]
 [0.18351814 0.14212707 0.927996   0.44974801]]


random sample with a range:
 [[-3.72929418  1.24295917  1.8040077   4.37740952]
 [-2.19979613 -2.04008613 -3.90458452  2.72976718]
 [ 2.76194438  2.31641551 -1.16567728 -0.31111729]]


In [34]:
# another example with an vector 
b,a = 5,-5
rsample = (b-a) * np.random.random_sample(size=(10,)) + a
# this will generates the 1d array or a vector in a range of [-5,5) 

print(rsample)

[ 1.54611098  2.11429992 -4.93073963 -0.70835665  4.18323288 -1.36067667
 -4.60723531  2.15059125  0.93310887 -1.47010793]


To understand the range concept we wil make another array in another range.

Target range:------> [5,0)

it means that our a = 5 and b = 0

now according to the the formula to create the range function is that we need to multiply `(b-a)` with  `rndom_sample()` and need to add `a`. by doing  this it will generate the random number in the Target range.

**Example 1**

In [63]:
# Taget range:----------> [0,5)  where b > a

b,a = 5 , 0 
line = 100
# a and b are taken from the range.
print(f"Lower range a: {a}")
print(f"Upper range b: {b}\n")

# Geenrating a 1d random array in the given range.

rsample = (b-a) * np.random.random_sample(size=(10,)) + a

print(f"\n {(b-a)} * {'np.random.random_sample(size=(10,))'} + ({a})")

# the above line can be written as the 5 * np.random.random_sample(size=(10,)) + 0
print(f"{'_'*line}")
print("\nrandom_sample in the half-open interval [0,5)\n\n", rsample)
print(f"{'_'*line}")

Lower range a: 0
Upper range b: 5


 5 * np.random.random_sample(size=(10,)) + (0)
____________________________________________________________________________________________________

random_sample in the half-open interval [0,5)

 [1.46044041 4.86694928 0.95407778 0.39286663 3.98789528 0.08531375
 3.82579891 4.46372758 0.21860775 1.16465465]
____________________________________________________________________________________________________


**Example 2**

In [62]:
# Taget range:----------> [-5,0) where b > a
line = 100

b, a  = 0, -5 # a and b are taken from the range.
# a and b are taken from the range.
print(f"Lower range a: {a}")
print(f"Upper range b: {b}\n")

# Geenrating a 1d random array in the given range.

rsample = (b-a) * np.random.random_sample(size=(10,)) + a
print(f"\n {(b-a)} * {'np.random.random_sample(size=(10,))'} + ({a})")
# the above line can be written as the 5 * np.random.random_sample(size=(10,)) - 5
print(f"{'_'*line}")
print("\nrandom_sample in the half-open interval [-5,0)\n\n", rsample)
print(f"{'_'*line}")

Lower range a: -5
Upper range b: 0


 5 * np.random.random_sample(size=(10,)) + (-5)
____________________________________________________________________________________________________

random_sample in the half-open interval [-5,0)

 [-2.10616978 -0.60560178 -2.86851344 -1.98063182 -3.04817592 -3.48397826
 -2.76213706 -2.17490407 -4.31277699 -3.21696853]
____________________________________________________________________________________________________


As we can see in the both Example 1 and the Example 2, we have got our desired result in the desired range as we thaught but still we need to understand that how it works, for that we need to break the code into three parts.

* random_sample()
* multiply (b-a) 
* add a

**Breaking the above result code**

first of all we need to see about the random_sample.

In [65]:
# creating the random sample to analysis it
np.random.random_sample(size=(10,))

array([0.32499663, 0.85421945, 0.50933069, 0.12742628, 0.97398831,
       0.34586032, 0.51319776, 0.67346228, 0.57546226, 0.42283627])

Now we can see that all the values are b/w the (0.0,1.0), From the documentation we have found that it generates the values in half-open interval in `[0.0, 1.0) ` 

So if we muliply it  from some value (X) then all the values multiplied from that valuea and we can generate values from 0 to X. 

In [69]:
# multiplying the random_sample form the X value
X = 5

rsample = X * np.random.random_sample(size=(10,))
print(rsample)

[0.72985836 0.05728082 2.16953448 4.11911885 1.16731283 0.25994343
 2.66289224 2.53783647 3.54802013 3.91487207]


As we can see that we have created values form the [0,5) but in this 5 is not incluive becaues 1 was not inclusive during the generation of the random values. so we can create the random values in b/w [0.0, 5.0) half open interval.

Now if we add some other value say Y in the `rsample` result then it will generate the number in b/w `[X,Y)` range in which X would be inclusive. 

`Note:` In this whole process Y > X

In [70]:
# since X > Y then Y should be small then the X so we take the Y as the -5

Y = -5

# adding the in the rsample
rsample + Y

array([-4.27014164, -4.94271918, -2.83046552, -0.88088115, -3.83268717,
       -4.74005657, -2.33710776, -2.46216353, -1.45197987, -1.08512793])

Now you can see that all the values are negative or we can say that all values are in b/w [0.0 ,  -5) . 

but if we take non negative value of Y then.

In [71]:
# taking the Y as positive and small to X

Y = 2  # Y < X

rsample + Y

array([2.72985836, 2.05728082, 4.16953448, 6.11911885, 3.16731283,
       2.25994343, 4.66289224, 4.53783647, 5.54802013, 5.91487207])

Now you can see that the range is changed from `[0.0 , 5.0)` ---------------------> `[2,0, 7.0)`

but the problem we didn't used the value 7.0 to get this range so what happend. Well this is just simple Mathematics. Let's break all the operations.

**Point 1**

In [72]:
np.random.random_sample(size=(10,))

array([0.16039843, 0.8577194 , 0.48684179, 0.59724195, 0.29276744,
       0.47218278, 0.70777807, 0.74815284, 0.98184573, 0.3069532 ])

_np.random.random_smple()_  generates some random values from 0 to 1 in float in which 1 is not inclusive so all the values are in b/w 0 to 1 but there will no 1 incuded.

**Point 2**

So if we muliply some X value then this X will be multiplied to all the values if we use the for loop to visulize the all computation then we can see that what is going on.

In [85]:
# Since we need to match the result so we will take the X as 5
X = 5

# but we need to create a fresh  a new rsample 

rsample = np.random.random_sample(size=(10,))

print("Our oringianl values are: \n\n", rsample)
# iterating over the all values 

print("\nOur new values after the multiplying the X values in the rsample\n")
for values in rsample:
    
    # using the rsample which is saved in the memories already and by this our result will match.

    # we will print all the vlaues to understand the computation
    
    print(f"{X} * {values} = {X*values}")

Our oringianl values are: 

 [0.99460423 0.10049994 0.1753754  0.34073775 0.72674755 0.09511575
 0.20043972 0.40826225 0.01564071 0.03258093]

Our new values after the multiplying the X values in the rsample

5 * 0.9946042292772675 = 4.973021146386338
5 * 0.100499937750122 = 0.50249968875061
5 * 0.1753754044201714 = 0.876877022100857
5 * 0.34073775476562507 = 1.7036887738281252
5 * 0.7267475490417133 = 3.633737745208567
5 * 0.09511575267932626 = 0.4755787633966313
5 * 0.20043971761490875 = 1.0021985880745437
5 * 0.40826224627998364 = 2.041311231399918
5 * 0.01564070869399925 = 0.07820354346999625
5 * 0.03258092719347494 = 0.1629046359673747


Now we use our direct mehod to multiply the vlaues to crate the array. 

In [86]:
X * rsample

array([4.97302115, 0.50249969, 0.87687702, 1.70368877, 3.63373775,
       0.47557876, 1.00219859, 2.04131123, 0.07820354, 0.16290464])

As you can see that all values are same to the above result by doing this we have created the range from 0 ot 5,

but now we will add the Y, but the Y is small to the X

In [87]:
Y =2
X * rsample + 2

array([6.97302115, 2.50249969, 2.87687702, 3.70368877, 5.63373775,
       2.47557876, 3.00219859, 4.04131123, 2.07820354, 2.16290464])

Now we will see the all values in the for loop

In [90]:
Y = 2
X_rsample = X*rsample

for values in X_rsample:
    
    print(f" {values} + {Y}  =  {values+Y}")

 4.973021146386338 + 2  =  6.973021146386338
 0.50249968875061 + 2  =  2.50249968875061
 0.876877022100857 + 2  =  2.876877022100857
 1.7036887738281252 + 2  =  3.7036887738281252
 3.633737745208567 + 2  =  5.633737745208567
 0.4755787633966313 + 2  =  2.4755787633966313
 1.0021985880745437 + 2  =  3.0021985880745437
 2.041311231399918 + 2  =  4.041311231399918
 0.07820354346999625 + 2  =  2.0782035434699964
 0.1629046359673747 + 2  =  2.162904635967375


Now we can see that we have got our new vlaues in the b/w the 2 to 7. From all of this we can say that range can be manuplate by using the X and Y but still we need to be clear that how we decide the range. use the all computation b/w the X and Y.

X = 5 ||
Y = 2

all possible computation are add, multiply, deivde, subtract.

`X + Y = 7 `       |       `X -Y = 3`         |            `X /Y = 2.5`           |           `X*Y = 10`

from this we have found the relation to get the final range of the values.

So we found two result as the range is that .

Y = 2 and X+Y = 7

Now if we take the `Y = a` as the lower range  and `X+Y = b` as the upper range in which *y > a*.

So from all this computation we have got the lower value and the upper value of the range.
Now the equation `X+Y=b` becomes `X+a = b`  and then X becomes  `X = b-a`.

In [93]:
# Now if we compute the above valus

X = 5
Y = 2

print(f" range :[{Y},{X+Y})")

 range :[2,7)


from the above result we have got the if we want to generate an array in b/w [a,b) range then as showing in the above reslut [2,7) we need to give the input as 

`lower range  = 2`  and `upper range = X + lower range`

but in the Above example we have used X and Y as to generate the random values `X*random_sample(size)+Y` but in after Computation this gives us the different range output from the input range as X and Y, but also we have found that our lower range is `lower range = a = Y`  and then the X becomes `             X = upper range - lower range` and we know that our lower range is `a` and the upper range `b`.

So X and Y becomes: 

`X = b-a`  

`Y = a`

So our equation of  `rsample = X * random_sample(size) + Y` becomes  ` rsample = (b-a) * random_sample(size) + a`. Where `a` is the lower value of the range and the `b` is the upper value of the range array.

Now we have understand the concept of the random_sample() now we will generate the values in b/w the [10 . 20)

In [97]:
# creating the values in b/w the the range [10 . 20) where b > a

# from the range we have
a = 10  # lower value
b = 20  # upper value

# so our final sample is

(b-a) * np.random.random_sample(size=(10,)) + a

array([16.8765738 , 14.22567961, 16.23765942, 15.52789411, 13.27575265,
       18.86995207, 19.56821628, 10.39116099, 14.54947583, 11.71462581])

From the above result we have got the desired result in b/w the 10 to 20.

***
***

## numpy.random.random_integer()

 This function is deprecated. Please call randint(L, H + 1)
 
 where L is the lower value and H is the higer vlaue

To sample from N evenly spaced floating-point numbers between a and b, use:

`a + (b - a) * (np.random.random_integers(N) - 1) / (N - 1.)`

In [99]:
np.random.random_integers(0,10 , size = (2,5))

<ipython-input-99-4a687f18bea8>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  np.random.random_integers(0,10 , size = (2,5))


array([[4, 1, 6, 6, 3],
       [6, 4, 3, 1, 6]])

**Since this function has been deprecated so we will use the randint**

Now we will do all the operation on the randint function 

***1. Generating an array using randint***

In [28]:
# Since randint is the similar function as the random_intergers

# Here we will generate an array with in 1 to 10 range. with a size of (2,10)
np.random.randint(1, 10, size=(2,10))

array([[6, 5, 9, 7, 4, 1, 1, 7, 6, 6],
       [5, 2, 9, 7, 3, 3, 7, 9, 2, 9]])

similarly here first argument is for the lower value of the range and the second value is for the higher value of the range.

***2. Generating N evenly spaced floating point b/w a and b***

In [30]:
# this is similar to the random_sample 
# here also we have a range [a,b] in which b > a 

a = 10 
b = 20 
N = 5

# for now we will simply put the method directly after that we will break it
# we will make an vector of 10 dimensions 

(b-a) * ( np.random.randint(N , size=(10, )) - 1 ) /(N - 1.0)  + a    

array([10. , 17.5, 17.5, 15. ,  7.5,  7.5, 15. , 17.5, 10. , 17.5])

As you can see that it generates some evenly spaced floating - point in b/w a and b.

Now we will break this code so we can understand that what is going on in this. Here we have four parts in this:

1. `(b-a)`
2. `( np.random.randint(N , size=(n,)) -1)`
3. `(N -1.)`
4. `a`


we have already seen the 1st and 4th part in the random_sample function so we will do not repeat it here. now we will focus on the only the 2nd and 3rd part of the code. So now will generates another sample and store it in a variable so we can track our result.

###### 1. Generating the sample

In [32]:
# genrating and storing it in a variable 
# here we will take the 5 as the N value.

sample = np.random.randint(5, size=(20, ))
print(sample)

[4 2 0 2 4 0 4 1 2 3 2 1 0 2 3 0 0 2 3 2]


Note that here we have passed only the low value in this case it genereates the values 0 to low value and in this case it generates 0 to 5 since it takes the low values as the high and low becomes 0.

Now it have generated some values from 0 to 5 so now we will subtract 1 from it.

###### 2. Subtracting the 1 from all vaues 

In [33]:
sample - 1

array([ 3,  1, -1,  1,  3, -1,  3,  0,  1,  2,  1,  0, -1,  1,  2, -1, -1,
        1,  2,  1])

As you can see that we have got all the values after minus one. Now we will devide it from the (N - 1.) where N is the low value which is passed in the low argument.

###### 3. deviding from (N -1.)

In [34]:
# deviding the sample -1 from the (N - 1.) 
(sample - 1) / (N -1.)

array([ 0.75,  0.25, -0.25,  0.25,  0.75, -0.25,  0.75,  0.  ,  0.25,
        0.5 ,  0.25,  0.  , -0.25,  0.25,  0.5 , -0.25, -0.25,  0.25,
        0.5 ,  0.25])

Now after deviding it we can see that the range of the output array becomes from `-1 to 1` . Now we can make our desired range because we have got the array range from `1 to 1`  and we can multiply and add in it to get the desired range.

###### 4. getting the N evenly spaced floating numbers.

We will seperate this in two parts:
1. multiply the `(b-a)`
2. add `a`

In [36]:
# we have already defined the a and b but we will again defining it.
a = 10 
b = 20   # b > a 
N = 5
# This is the range in b/w we are going to making the floating points.

(b-a) * (sample -1)/(N -1.)

array([ 7.5,  2.5, -2.5,  2.5,  7.5, -2.5,  7.5,  0. ,  2.5,  5. ,  2.5,
        0. , -2.5,  2.5,  5. , -2.5, -2.5,  2.5,  5. ,  2.5])

By multplying `(b-a)` we have generated the values below a now to get over desired result we will add `a` in above result. by multiplying the `(b-a)` the range of the array becomes [-9 ,  10]

In [37]:
(b-a) * (sample -1)/(N -1.) + a

array([17.5, 12.5,  7.5, 12.5, 17.5,  7.5, 17.5, 10. , 12.5, 15. , 12.5,
       10. ,  7.5, 12.5, 15. ,  7.5,  7.5, 12.5, 15. , 12.5])

As you can see that we have got some values which are in  b/w 10 to 20.  By adding `a` the lower value of the range all the values are shifted in b/w a and b .

Now we will make a function which will make all above result in single hit and we will be able to see this result on different N values.

#### randint_float_sample()

In [40]:
def randint_float_sample(N, shape, a,b):
    
    """ This function will generate N evenly spaced floating-points in b/w a and b values and also it will so all operation of 
    generating the sample
    
    N = This is the lowest value for the randint() function and also it will be used to make the even space b/w values.
    shape = this is the shape of the output array
    
    a = This is the lower value of the range [a,b]
    b = This is the highest value of the array or sample in range [a,b]
    """
    
    # output result
    # (b-a) * ( np.random.randint(N , size= shape) - 1 ) /(N - 1.0)  + a    
    
    # first of all we need to generate a randint sample with a size and N .
    
    sample = np.random.randint(N, size = shape)
    
    #  Need to print the original sample
    print("1. Our original sample:\n",sample)
    
    # now we will do sample -1 operation
    sample =  sample -1
    
    # need to print new sample which have all new values less one from the original
    print("\n2. Sample after 'sample -1':\n",sample)
    
    # now we need do devide the (N -1.) from the new sample
    sample = sample / (N -1.)
    
    # printing the new sample
    print(f"\n3. Sample after '(sample - 1) / ({N} - 1.)':\n", sample)
    
    # now we will multiply the (b-a) to sample
    sample = sample * (b-a)
    
    # printing the new sample
    print(f"\n4. Sample after '({b}-{a}) * (sample - 1)/ ({N}-1.) ':\n", sample)
    
    # adding a into the newest sample
    sample = sample + a
    
    # printing the finale result
    print(f"\n5. Sample after '({b}-{a}) * (sample - 1) /({N} - 1.0)  + {a} ':\n",sample)


**Example 1**

In [41]:
randint_float_sample(5,(10,),10,20) 

1. Our original sample:
 [3 3 2 0 2 2 4 2 1 2]

2. Sample after 'sample -1':
 [ 2  2  1 -1  1  1  3  1  0  1]

3. Sample after '(sample - 1) / (5 - 1.)':
 [ 0.5   0.5   0.25 -0.25  0.25  0.25  0.75  0.25  0.    0.25]

4. Sample after '(20-10) * (sample - 1)/ (5-1.) ':
 [ 5.   5.   2.5 -2.5  2.5  2.5  7.5  2.5  0.   2.5]

5. Sample after '(20-10) * (sample - 1) /(5 - 1.0)  + 10 ':
 [15.  15.  12.5  7.5 12.5 12.5 17.5 12.5 10.  12.5]


**Example 2**

In [43]:
randint_float_sample(10,(10,),10,20) 

1. Our original sample:
 [2 2 1 9 8 8 2 1 2 6]

2. Sample after 'sample -1':
 [1 1 0 8 7 7 1 0 1 5]

3. Sample after '(sample - 1) / (10 - 1.)':
 [0.11111111 0.11111111 0.         0.88888889 0.77777778 0.77777778
 0.11111111 0.         0.11111111 0.55555556]

4. Sample after '(20-10) * (sample - 1)/ (10-1.) ':
 [1.11111111 1.11111111 0.         8.88888889 7.77777778 7.77777778
 1.11111111 0.         1.11111111 5.55555556]

5. Sample after '(20-10) * (sample - 1) /(10 - 1.0)  + 10 ':
 [11.11111111 11.11111111 10.         18.88888889 17.77777778 17.77777778
 11.11111111 10.         11.11111111 15.55555556]


**Example 3**

In [47]:
randint_float_sample(15,(5,3,),10,20) 

1. Our original sample:
 [[14 10  1]
 [ 8  5  1]
 [14 13 14]
 [ 3 10  3]
 [ 6  9  8]]

2. Sample after 'sample -1':
 [[13  9  0]
 [ 7  4  0]
 [13 12 13]
 [ 2  9  2]
 [ 5  8  7]]

3. Sample after '(sample - 1) / (15 - 1.)':
 [[0.92857143 0.64285714 0.        ]
 [0.5        0.28571429 0.        ]
 [0.92857143 0.85714286 0.92857143]
 [0.14285714 0.64285714 0.14285714]
 [0.35714286 0.57142857 0.5       ]]

4. Sample after '(20-10) * (sample - 1)/ (15-1.) ':
 [[9.28571429 6.42857143 0.        ]
 [5.         2.85714286 0.        ]
 [9.28571429 8.57142857 9.28571429]
 [1.42857143 6.42857143 1.42857143]
 [3.57142857 5.71428571 5.        ]]

5. Sample after '(20-10) * (sample - 1) /(15 - 1.0)  + 10 ':
 [[19.28571429 16.42857143 10.        ]
 [15.         12.85714286 10.        ]
 [19.28571429 18.57142857 19.28571429]
 [11.42857143 16.42857143 11.42857143]
 [13.57142857 15.71428571 15.        ]]


**Example 4**

In [48]:
randint_float_sample(20,(10,2),10,20) 

1. Our original sample:
 [[ 8 12]
 [ 5 13]
 [12  7]
 [ 7  3]
 [ 3 14]
 [11 14]
 [11  8]
 [ 8 16]
 [ 1 13]
 [14 14]]

2. Sample after 'sample -1':
 [[ 7 11]
 [ 4 12]
 [11  6]
 [ 6  2]
 [ 2 13]
 [10 13]
 [10  7]
 [ 7 15]
 [ 0 12]
 [13 13]]

3. Sample after '(sample - 1) / (20 - 1.)':
 [[0.36842105 0.57894737]
 [0.21052632 0.63157895]
 [0.57894737 0.31578947]
 [0.31578947 0.10526316]
 [0.10526316 0.68421053]
 [0.52631579 0.68421053]
 [0.52631579 0.36842105]
 [0.36842105 0.78947368]
 [0.         0.63157895]
 [0.68421053 0.68421053]]

4. Sample after '(20-10) * (sample - 1)/ (20-1.) ':
 [[3.68421053 5.78947368]
 [2.10526316 6.31578947]
 [5.78947368 3.15789474]
 [3.15789474 1.05263158]
 [1.05263158 6.84210526]
 [5.26315789 6.84210526]
 [5.26315789 3.68421053]
 [3.68421053 7.89473684]
 [0.         6.31578947]
 [6.84210526 6.84210526]]

5. Sample after '(20-10) * (sample - 1) /(20 - 1.0)  + 10 ':
 [[13.68421053 15.78947368]
 [12.10526316 16.31578947]
 [15.78947368 13.15789474]
 [13.15789474 11

### Note:
As you can see that Whatever the N is but the values of the array are in the range of `[a , b]`. 

So this is how we can generates some floating point from randint function.

***
***

## numpy.random.choice()
```ruby
random.choice(a, size=None, replace=True, p=None)
```

Generates a random sample from a given 1-D array


`a:`
If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if a were np.arange(a)

`size:`
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

`replace:`
Whether the sample is with or without replacement

`p:`
The probabilities associated with each entry in a. If not given the sample assumes a uniform distribution over all entries in a.

This choice function is basically used to pick someting from a sample space randomly. or like generating an event randomly such as Head and Tail of the coins, rolling of six side die and randomly getting any number b/w 1 to 6. We we see some example to understand that how choice function works.

###### 1. Generate a uniform random sample from `np.arange(5)` of size `3`:

In [52]:
print("array sampel from the np.arange(): ",np.arange(5))

# uniform sample by using the random.choice()
np.random.choice(5,3)

# here 5 is a= 5 and 3 is the size = (3,) 1d array

array sampel from the np.arange():  [0 1 2 3 4]


array([1, 0, 4])

As you can see that here `np.arange()` function genretes a perfect array in a series but the choice has `a=5` in this a is int and it will select any number from 0 to 4 and Since we have given that we need an array of `size = (3,)` so  it generates 3 elements.Let's now see the above code with the help of the for loop. 

In this for loop we will pick any number b/w 0 to 5 and loop will run up to 10 to 20 times.

In [57]:
# we will run a loop two times 1st loop is 10 times and 2nd loop will run 20 times
print("1st Loop")
for i in range(10):
    print(np.random.choice(5), end=",")
    
print("\n\n2nd Loop")
for i in range(20):
    print(np.random.choice(5), end=",")

1st Loop
1,4,1,1,3,1,2,2,1,1,

2nd Loop
2,4,0,0,1,4,1,4,2,2,4,3,2,0,1,0,2,2,3,3,

As you cnd see that this choice function randomly choose one element form 0 to 4 but do not include 5 in picking, because when we pass an integer this will generats a `np.arange(5)` array and pass it to `a` then it randomly pick values from it. 

Now this time we will pass a `np.arange(n)` into `a`.

In [59]:
# passing a np.arange(n) into a 
arange = np.arange(5)

print("Our np.arange values are: ",arange)

# passing to a in the choice function

print("1st Loop")
for i in range(10):
    print(np.random.choice(arange), end=",")
    
print("\n\n2nd Loop")
for i in range(20):
    print(np.random.choice(arange), end=",")

Our np.arange values are:  [0 1 2 3 4]
1st Loop
0,0,0,2,3,2,2,2,1,1,

2nd Loop
2,0,3,1,4,2,1,2,3,3,4,3,4,0,1,1,3,2,4,3,

###### 2. Generate a non-uniform random sample