# Introduction

There are 5 general mechanisms for creating arrays:

1. Conversion from other Python structures (e.g., lists, tuples)
2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions (e.g., random)

This section will not cover means of replicating, joining, or otherwise expanding or mutating existing arrays. Nor will it cover creating object arrays or structured arrays. Both of those are covered in their own sections.

# Numpy Data Science basic operations.

In this tutorial we will perform some of the basic operation of the numpy array such as..

* Creating array
* Getting the array size
* accessing the array elements 
* slicing the array

Importing the numpy module

In [2]:
import numpy as np

# 1. Creating an array 
In this section we will see the creation of the array and what are the ways to create the array using the numpy mdule. first of all we will see the `numpy.array()` module which can be used to create an nd-array.

```ruby
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```
For documentation see the below like.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html?highlight=numpy%20array#numpy.array">numpy.array()</a>

First of all we will see that how we create an arrya object with the help of the `numpy.array()` and the list.

Suppose that we have a list: 
```ruby
List: [1,2,3,4,5,6] 
```
Now we will pass that list into the numpy.array() in object parameter.
```ruby
object: # object is a variable or instance which holds the values or the data strucuture which need to be converted into the numpy array.

dtype: # dtype will defines the data type of the array which we are creating, you should check the tutorial on Numpy data types.
```

For now we will only see these two parameters of the.

In [3]:
# creating the numpy array with numpy.array()
List = [1,2,3,4,5,6] 
array1 = np.array(List,int) # here first parameter is object and the second one is for the datatype of the numpy object

print(array1)

[1 2 3 4 5 6]


In [4]:
array1

array([1, 2, 3, 4, 5, 6])

## Creating multi dimensional array

Suppose that we have two list or a nested list with two sub list then if we pass thid nested list into the array object we can create the nd- array.

```ruby
List1 : [1,2,3,4,5,6,7,8,9]
List2 : [1,2,3,4,5,6,7,8,9]
List3 : [1,2,3,4,5,6,7,8,9]
```
Now we have three list, we will use them to create the nd-array

In [10]:
List1 = [1,2,3,4,5,6,7,8,9]
List2 = [1,2,3,4,5,6,7,8,9]
List3 = [1,2,3,4,5,6,7,8,9]

# now we have three list list1, list2, list3 
# making a 2d array

array_2d = np.array([List1, List2], int)

# pritnting the array 
print("this is my 2d array: \n", array_2d)

array_2d = np.array([List1,List2,List3])

# printing the array
print("\nthis is my another 2d array: \n", array_2d)

this is my 2d array: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]

this is my another 2d array: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


As you can see that we have made a numpy array with the help of the numpy.array() and a list. We can also use the tuple insted of the list.

For now we will not see the 3d array we will make a seprate array on the 3d array.

Now we will see some inbuilt function to create the array.

***

## Creating array with some inbuilt function of the numpy

Numpy module is a wast module operation on the array or multi dimensional array in which we have some inbult funciton which can create a particular type of array. LIke:

* zeros()
* ones()
* empty()
* full()
* arange()
* linspace()
* indices()
* empty_like()
* zeros_like()
* ones_like()
* full_like()

## Zeros array

we can make the zeros array with a shape.

```ruby
zeros(shape, dtype=float, order='C', *, like=None)
```
Return a new array of given shape and type, filled with zeros.
 
 You can see the additional reference of the numpy.zeros form the link.
<a href="https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=numpy%20zeros#numpy.zeros">numpy.zeros()</a>

In [14]:
# here also we will see the most commonly used parameters 
# shape: this will define the shape of the array and it takes a list or a tuple as input
# dtype: this will define the data type of the array.

# 1. dtype: int    and  shape:(2,2)
zeros_array = np.zeros((2,2), dtype=int)

print("This is the int type (2,2) array:\n",zeros_array)

# 1. dtype: float    and  shape:(3,2)
zeros_array = np.zeros((3,2), dtype=float)
print("\nthis is the float type (3,2) array:\n",zeros_array)

This is the int type (2,2) array:
 [[0 0]
 [0 0]]

this is the float type (3,2) array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


Here array is created in this format ----> (R,C,P)
* R: Rows
* C: Columns
* P: Plane

## Ones array

Now we will see ones array and the syntax is:
```ruby
 np.ones(shape, dtype=None, order='C', *, like=None)
```
Return a new array of given shape and type, filled with ones.



In [15]:
# now we will se ones array with int and float data type

# dtype: int     and   shape: (2,2)
ones_array = np.ones((2,2),int)
print("This is the ones array of int type and a shape of (2,2) :\n", ones_array)

# dtype: int     and   shape: (3,2)
ones_array = np.ones((3,2),float)
print("\nThis is the ones array of float type and a shape of (3,2) :\n", ones_array)

This is the ones array of int type and a shape of (2,2) :
 [[1 1]
 [1 1]]

This is the ones array of float type and a shape of (3,2) :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
np.empty()

## Empty array
Now we will see the empty array

```ruby
np.empty(shape, dtype=float, order='C', *, like=None)
```
Return a new array of given shape and type, without initializing entries.

For furthur detail see this: 
<a href="https://numpy.org/doc/stable/reference/generated/numpy.empty.html?highlight=numpy%20empty#numpy.empty">numpy.empty() </a>
    

In [33]:
# now we will see the empty array of n-shape

# dtype: int    and          shape:(2,2)
empty_array = np.empty((2,3), int)
print("This is the empty array of int type and a shape of (2,2) :\n", empty_array)


# dtype:float    and          shape:(2,4)
empty_array = np.empty((2,4), float)
print("\nThis is the empty array of float type and a shape of (2,3) :\n", empty_array)

This is the empty array of int type and a shape of (2,2) :
 [[-1997275216         453           0]
 [          0           1  2098768637]]

This is the empty array of float type and a shape of (2,3) :
 [[0.00e+000 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 4.07e-321 0.00e+000 0.00e+000]]


`Note:` empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

## Full array
Now we will see the full array, creatinf full arry is different form the above defined arrays.

```ruby
 np.full(shape, fill_value, dtype=None, order='C', *, like=None)
```
Return a new array of given shape and type, filled with `fill_value`.

See the full documentation on the `numpy.full()` array: 
<a href="https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full">numpy.full()</a>


In [37]:
# now we will see the full array in the numpy module 
# Since this full array is different from the other whcih is defined above so we will see in details

# the main thing which is different in this is that fill_values.
# so we will do some work on the fill_values.

# dtype: int       and          shape:(2,2)
full_array = np.full((2,2),int)
print("This is the full array of int type and the shape is (2,2) : \n",full_array)

# dtype: float       and          shape:(2,4)
full_array = np.full((2,4), float)
print("\nThis is the full array of float type and the shape is (2,4) : \n",full_array)

This is the full array of int type and the shape is (2,2) : 
 [[<class 'int'> <class 'int'>]
 [<class 'int'> <class 'int'>]]

This is the full array of float type and the shape is (2,4) : 
 [[<class 'float'> <class 'float'> <class 'float'> <class 'float'>]
 [<class 'float'> <class 'float'> <class 'float'> <class 'float'>]]


Now we have done the same thing which have made in previous all of the array but in this case we can see that there is no values in this. Because in this we need to provide the values in the `fill_values` parameters.

So, let's do some test with some values.

#  Non-square shape full array

## Case 1: Only passing a single value to fill_vlaue 

In [38]:
# in this we will provide only one value 

# dtype : int       shape: (2,3)      fill_value:[1]
# carefull: here the second parameter is "fill_values" so we need to pass some values in that
np.full((2,3),[1],int )

array([[1, 1, 1],
       [1, 1, 1]])

Note: we need to see the above output. in this result we have made an array a shape of (2,2) and only passed [1].

In this case 1 will be filled to all allocated location. 

***

## Case 2: Passing two values to fill_vlaue

In [41]:
# in this we will provide two value 

# dtype : int       shape: (2,3)      fill_value:[1,2]
# carefull: here the second parameter is "fill_values" so we need to pass some values in that
np.full((2,3),[1,2],int )

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

`Note:` We can see that when we try to pass value which are not equal to the column of the shape of the array. Then it will show the ValueError message.
like,
```ruby
List: [1,2] or [1,2,3,4]
```

**Now we will pass the values equal to the column of the array**

In [46]:
# in this we will provide three value 

# dtype : int       shape: (2,3)      fill_value:[1,2,3]
# Carefull: here the shape of the array is (2,3)
# then the column values should be 3.

np.full((2,3),[1,2,3],int )

array([[1, 2, 3],
       [1, 2, 3]])

Now we can see the we have created the an array with a shape of (2,3) and fill_values:[1,2,3].

But as you can notice that these values are repeting in each row. So if we dont want to repeat the values in the row then what?

**Now we will give the values equal to the rows and columns**

In [47]:
# in this we will provide two list containg the equal value 

# dtype : int       shape: (2,3)      fill_value:[1,2,3],[4, 5,6]
# Carefull: here the shape of the array is (2,3)
# then the column values should be 3.
# and rows are 2.

np.full((2,3),[[1,2,3],[4,5,6]],int )

array([[1, 2, 3],
       [4, 5, 6]])

Now as you can see that we have eleminate the problem of repetation of the values by providing the values equl to the rows and columns. 

`Note:` Be carefull when passing the *fill_values*. it should be equal to the number of columns or both columns and rows.

**Now we will double the shpae of the previous one**

In [50]:
# in this we will increase the colulmns by twice but the input will be same as was in previous one.

# dtype : int       shape: (2,3)      fill_value:[1,2,3],[4, 5,6]
# Carefull: here the shape of the array is (2,3)
# then the column values should be 3.
# and rows are 2.

np.full((2,6),[[1,2,3],[4,5,6]],int )

ValueError: could not broadcast input array from shape (2,3) into shape (2,6)

`Error:` As can see that we have *ValueError* because we didn't pass the values in the right shape. So to solve this problem we have three option.

* We can pass a single value which will fill all the (i,j) loaction
* We can pass a single list which will fill the all row with same values.
* We can pass an array or array_like object with the same shape of the current one. Like if the shape of the current full() array is (4,6) then we can pass an array with this shape.

But for now we will only do the first two method.

#### Method 1

In [51]:
np.full((2,6),[1],int )

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### Method 2

In [53]:
np.full((2,6),[1,2,3,4,5,6],int )

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [54]:
np.full((6,2),[1,2],int )

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

`Note:` As we can see that we have resolved the ValueError problem in this by using the first two methods.

We didn't use the third method because if we want to fill all the values by ourself then we should use the *numpy.array()* funtion not this *numpy.full()* funtion to create an array which is having the all vlaues defined by user.